# -*- coding: utf-8 -*-
# Python data of Singpho dictionary + preconverted Assamese

# Assamese encoded with 'Tanmatra Boishakhi'.

sgp_assamese_info = [
    [   0, "à", "Awxgh|êw\ Ìpw\w„"],
    [   1, "á", "ÌLwlw„"],
    [   2, "ah", "A’!"],
    [   3, "àng", "lMw, lq„"],
    [   4, "áng", "ÌUUÖ„"],
    [   5, "âng", "ÌU#„"],
    [   6, "á", "oËìæwxnZ Ìpw\w, DÒZ Ìpw\w„"],
    [   7, "ai", "GK, p’t, hwl„"],
    [   8, "aima", "GUw, GxU, GM´wKy„"],
    [   9, "akam", "xgmòodyt„"],
    [  10, "akyen", "Udw„"],
    [  11, "akót", "pwZ ÌowËiw\w, UwdÐK LÖRw„"],
    [  12, "ahkâ", "oit, Kwl„"],
    [  13, "ahkying", "oit, Kwl„"],
    [  14, "ahkrit", "htwdK„"],
    [  15, "ahkyè", "Udw„"],
    [  16, "agang", "Udw„"],
    [  17, "agu", "LÖëbw ÌLw\w„"],
    [  18, "aka", "KwxtK Ìgbdw eÞKwm K´w GxU m²„"],
    [  19, "aku/agu", "Ìepw„"],
    [  20, "akyang", "Ahøwo,Èhw\„"],
    [  21, "akyu", "eÔYø, lwh„"],
    [  22, "ahkáng", "AdÖixZ„"],
    [  23, "ahkung", "oRyx\, Ryx\Z„"],
    [  24, "ahkun", "QÖxU, xgËgK„"],
    [  25, "ahkun", "Kr, LwRdw„"],
    [  26, "angang", "mKU, Uwd„"],
    [  27, "angok", "iÔLê„"],
    [  28, "angui", "lwËp gw lwËp-lwËp„"],
    [  29, "achyi", "ÌbEZw„"],
    [  30, "atsá", "ÌiwiwB„"],
    [  31, "atsam", "eÞxZhw, mx£ß, gl„"],
    [  32, "atsòm", "Â\dy, cÖdytw„"],
    [  33, "atsin", "xd´\Zw„"],
    [  34, "aten", "oit„"],
    [  35, "ahtu", "LÖëbw ÌLw\w„"],
    [  36, "adit", "Z"],
    [  37, "adok", "ÌRwKw, Ìcily K´w„"],
    [  38, "adót", "†xs K´w, UOxdtw„"],
    [  39, "atsàng", "K’lw„"],
    [  40, "atsâng", "ewZl, pwlKw„"],
    [  41, "atsang-alan", "xdËQB K’lw„"],
    [  42, "atsit", "ÌoExRtw„"],
    [  43, "a", "bq, ewMêZ„"],
    [  44, "aña", "iÔLê„"],
    [  45, "atú", "dKxl„"],
    [  46, "ateng", "bwxs xPpØ„"],
    [  47, "atung", "AwewËbE„"],
    [  48, "ahtik labau", "BxZpwo, e´óe´w„"],
    [  49, "adui", "AwÐg„"],
    [  50, "anau", "o´Ø hwB gw hxd„"],
    [  51, "anu", "iw, iwZÙ„"],
    [  52, "apelepa", "Ìg#¦ ciêZ EËÁLø Pwx´xgc d´K; ÌjËd (K) d´K, (L) Ì´#´\\, (M) ipw Ì´#´\\ Zaw (N) Ax\\xP„ GB m²xU giwê hwnw´ e´w ov¢ØiY ÑpxQl„"],
    [  53, "apu", "ÌbEZw„"],
    [  54, "ahpu", "KKwBËbE„"],
    [  55, "abá", "gwBËbE„"],
    [  56, "abet", "ewe, bÖûKiê„"],
    [  57, "am", "ÌKPÖ\\w l’´w„"],
    [  58, "amang", "pwlcytw g´Y„"],
    [  59, "amat", "iìèy„"],
    [  60, "amu", "Kwi,KZêgø„"],
    [  61, "amying", "Awšw„"],
    [  62, "amyu", "RwxZ, gMê„"],
    [  63, "amyu", "šwxZ gMê„"],
    [  64, "amoi", "Ìepy„"],
    [  65, "ara", "gÉ, p’g„"],
    [  66, "arut", "Ehwxl ÌeËlw\\w„"],
    [  67, "ayà", "hwl ÌZËdpËl„"],
    [  68, "ayâ", "Awšw„"],
    [  69, "arang", "AxcKw´ K´w, Awt£ K´w, ÌMwUwB ´Lw„"],
    [  70, "ari", "bëb, mwxþæ„"],
    [  71, "arai", "gt gþç„"],
    [  72, "aróng", "xK´Y, Ìewp´„"],
    [  73, "alaka", "GËdB„"],
    [  74, "alân", "cµR, eZwKw„"],
    [  75, "along", "K×iw´„"],
    [  76, "ali", "hwx´„"],
    [  77, "alû", "bwd bxqYw„"],
    [  78, "alun", "E´Ø\\wB ÌeËlw\\w„"],
    [  79, "awá", "xeZwB„"],
    [  80, "awang", "AwPx´Z, AwúPjê„"],
    [  81, "awut", "f×xK xbtw„"],
    [  82, "awun", "xgmÙvLlK´w„"],
    [  83, "asán", "exg¢, Qwf, Ail„"],
    [  84, "asuya", "P´Kw´„"],
    [  85, "ahung", "LøwxZ, ÌM#´\\„"],
    [  86, "î", "Awxi, AwiwËlwK„"],
    [  87, "ìng", "eöwxgZ„"],
    [  88, "îhteng", "Awxi„"],
    [  89, "îna", "Awiw´„"],
    [  90, "ip", "lÖKwB ´Lw, †® ´Lw„"],
    [  91, "u", "P´wB xPx´KxZ, eqy„"],
    [  92, "uhká", "KwD´y„"],
    [  93, "uhkam", "xPxUKw„"],
    [  94, "uhkying", "Gxgc hwËU#„"],
    [  95, "uhkù", "KËe# P´wB„"],
    [  96, "uhkoi", "P´wB Ìew\\wly„"],
    [  97, "ugan", "gd´ytw K×K×´w„"],
    [  98, "ugyé", "hwËU#„"],
    [  99, "ugut", "gto„"],
    [ 100, "ugum", "o¬øw´ oit„"],
    [ 101, "utsa", "NdxPx´Kw„"],
    [ 102, "ujui", "pwlcytw P´wB„"],
    [ 103, "utù", "dylw g´Y´ KËe#„"],
    [ 104, "udî", "KYy„"],
    [ 105, "unà", "iw†´„"],
    [ 106, "up", "ewld K´w gw mwod K´w„"],
    [ 107, "upa", "oiþæ„"],
    [ 108, "uphkang", "mwod K´w„"],
    [ 109, "ubyit", "Gxgc cwd ÌLw\\w P´wB„"],
    [ 110, "uyen", "mwxlKy P´wB„"],
    [ 111, "uyun", "Dbøwd„"],
    [ 112, "ura", "iZw K×K×´w„"],
    [ 113, "urì", "gd-K×K×´w„"],
    [ 114, "uróng", "Z"],
    [ 115, "ulá", "iZw K×K×´w„"],
    [ 116, "ulát", "´wxZ´ eÞai eÞp´„"],
    [ 117, "ulong", "K×K×´w Mswl„"],
    [ 118, "uloi", "gd´ytw i’p„"],
    [ 119, "uloi-hká", "ÌpËUKËZxK„"],
    [ 120, "ên", "GË´w\\w, gLlytw„"],
    [ 121, "èp", "IP´, ÌUiw."],
    [ 122, "é", "AËeqw K´w„"],
    [ 123, "ok", "oiw®, Aìæ„AxcK i´i ÌbLÖ\\w„"],
    [ 124, "ogogoi", "ÌMw\\w„"],
    [ 125, "ong", "Awdëb, oËìæwn„"],
    [ 126, "ong", "Rt, xRKw„"],
    [ 127, "ong-poi", "Awdëb´ Ìilw„"],
    [ 128, "ora", "dÙZø´ oitZ eÞKwm K´w còxd„"],
    [ 129, "oi", "AB„"],
    [ 130, "kakâ", "ÑggYê„"],
    [ 131, "kagá", "Adø, ÌgËlM„"],
    [ 132, "kang", "ZeËZw\\w, ÌoKw xbtw„"],
    [ 133, "kanghkau", "AwKwm, ÈMê„"],
    [ 134, "kachin", "D£´y iøwdiw´Z gwo K´w xPvËf# eÞRw„"],
    [ 135, "katsan", "Aewt, d´K„"],
    [ 136, "katé", "CUw„"],
    [ 137, "kadu", "ÌKËKêUÖ\\w„"],
    [ 138, "kani", "Kwxd„"],
    [ 139, "kaniya", "Kwxdtw„"],
    [ 140, "kanoi", "´g´„"],
    [ 141, "kamu", "KwVf×lw„"],
    [ 142, "kayà", "ÌKwil„"],
    [ 143, "kayut", "Dx¥edw„"],
    [ 144, "kara", "PÖxl„"],
    [ 145, "karan", "Kx´ Kxstw Ìow´w„"],
    [ 146, "kalá", "hw´Zyt„"],
    [ 147, "kalá-tâ", "---iwp„"],
    [ 148, "kalá", "hw´Z gnê„"],
    [ 149, "kalí", "ÌcdÖ„"],
    [ 150, "kalí", "gwZly †xU„"],
    [ 151, "kawá", "gwp„"],
    [ 152, "kawá", "gwpgwx´„"],
    [ 153, "kawá", "gwp´ U×K×´w„"],
    [ 154, "kà", "Ìow´w„"],
    [ 155, "kàng", "AwVÖ\\w Z´w„"],
    [ 156, "kàt", "gRw´, gÉZ Uwd„"],
    [ 157, "kàn", "ÌeU„"],
    [ 158, "kàp", "lwxM c´w„"],
    [ 159, "kàm", "BâQw K´w, id lMw„"],
    [ 160, "kàmhpa", "Kùe„"],
    [ 161, "kâ", "xlLw, A^Kw„"],
    [ 162, "kâmang", "Z"],
    [ 163, "káng", "Kr, Ìo\\w,´qw K´w„"],
    [ 164, "kát", "KUKxUtw„"],
    [ 165, "káp", "Kùe, bwd K´w„"],
    [ 166, "kám", "hwMø, Kewl„"],
    [ 167, "káya", "Kwt, m´y´„"],
    [ 168, "kran", "MQ KUw„"],
    [ 169, "kálà", "Kwl„"],
    [ 170, "kyí", "ewZZ xbtw, NÖ´w„"],
    [ 171, "kyin", "gøþæ, Kwjøê´Z„"],
    [ 172, "kyíp", "ÂKwB Ìjw\\w,i´xp Ìjw\\w„"],
    [ 173, "kung", "jZ´, ewMêZ„"],
    [ 174, "kun", "Kw-eÖ´Øn„"],
    [ 175, "kùm", "AwËMw´w, Ìgsw xbtw„"],
    [ 176, "kùmchyai", "gwxl„"],
    [ 177, "kumla", "g"],
    [ 178, "kong", "AwVÖ\\w Z´w„"],
    [ 179, "k", "Gxgc ÌXwl„"],
    [ 180, "kongpan", "ewdyË´ NÖË´w\\wGxgcgwp´ jìè„"],
    [ 181, "kongset", "xfQKwx´„"],
    [ 182, "kóng", "gwi iwxU„"],
    [ 183, "kò", "xPvËf# ex´twl´ eÞai bÖxpZw„K×K×´w Ìew\\wly xbtw„"],
    [ 184, "k", "oÖ´xqZ ´Lw„"],
    [ 185, "kóhka", "KwD´y„"],
    [ 186, "kóhpa", "†icwd„"],
    [ 187, "kai", "xPvËf# ex´twl´ eéi bÖxpZw„"],
    [ 188, "kaihtum", "K"],
    [ 189, "kailang", "K"],
    [ 190, "kài", "Kxe¬w (KwYfÖxl BZøwxb„"],
    [ 191, "kau", "ÌeËlw\\w, ZøwM K´w„"],
    [ 192, "koi", "A^wZ´w, dÖB K´w„"],
    [ 193, "hkà", "ewdy, dby„"],
    [ 194, "hkà", "gMly„"],
    [ 195, "hkâ", "Kwl„"],
    [ 196, "hká", "KFY, xPvËf# ex´twl´ 6Å bÖxpZw, xZZw„"],
    [ 197, "hkagai", "DeK×l„"],
    [ 198, "hkàng", "g¬w„"],
    [ 199, "hkâng", "ÌLwR, iwR„"],
    [ 200, "hkâng", "awcw„"],
    [ 201, "hkáng", "dMw RwZyt oiÔp„"],
    [ 202, "hkàngse", "K×ºy´„"],
    [ 203, "hkàt", "e´w, jÖRw„"],
    [ 204, "hkát", "Ròlw„"],
    [ 205, "hkà", "gwY-ewdy„"],
    [ 206, "hkà", "eÖLÖ´y, e´yLw„"],
    [ 207, "hkan", "Ìpewp„"],
    [ 208, "hkàn", "PÖ\\w, þemê K´w, Pwxëb Ìjw\\w„"],
    [ 209, "hkân", "Rwl i´w, ew´„"],
    [ 210, "hkanu", "dby„"],
    [ 211, "hkaman", "xixQiy ÌlwK„"],
    [ 212, "hkamdi", "LwiUy ÌlwK„"],
    [ 213, "hkalum", "Awb´Yy RËdw\\w, lMZ Ìjw\\w„"],
    [ 214, "hkàp", "RÖxe aKw, MÞpY K´w, Këbw„"],
    [ 215, "hkàm", "meU ÌLw\\w, iwxd Ìlw\\w„"],
    [ 216, "hkà", "dwb, eÖLÖ´y„"],
    [ 217, "hkà-man", "dby´ ÌmÞwZ„"],
    [ 218, "hkarang", "SÔi ÌLxZ´ eaw´„"],
    [ 219, "hkà", "dwI„"],
    [ 220, "hkà", "ewdy´ Ìo^wZ„"],
    [ 221, "hkàshi", "o´Ø dby, RÖx´„"],
    [ 222, "hkà", "Mw Ìcw\\w„"],
    [ 223, "hkà-wam", "Ñg daKw ewdy„"],
    [ 224, "hkì", "MÖVw, xo gw ÌZI^„"],
    [ 225, "hking", "owR, owRew´, ovÆÚxZ„"],
    [ 226, "hkit", "´RZ, xPlhw´„"],
    [ 227, "hkintông", "Z´w„"],
    [ 228, "hkinyamsring", "ÌZRxetw„"],
    [ 229, "hkyí", "†, il„"],
    [ 230, "hkying", "oit„"],
    [ 231, "hkying", "pwRw´„"],
    [ 232, "hkrang", "RKw, AwËlL„"],
    [ 233, "hkring", "aKw, ´Lw, þæ² ´Lw, g¬ Ìpw\\w„"],
    [ 234, "hkringdat", "xVKdw„"],
    [ 235, "hkringmang", "KUKy„"],
    [ 236, "hkrit", "ht lMw, ht ÌLw\\w„"],
    [ 237, "hkritung", "Mhê\\Zy A\\þÿw„"],
    [ 238, "hkui", "xPKw´ K´w, iwQ c´w„"],
    [ 239, "hkuk", "RwÐK„"],
    [ 240, "hkung", "oRyx\\, ÌiR„"],
    [ 241, "hkungrang", "cËdm eqy„"],
    [ 242, "hkungran", "xggwp„"],
    [ 243, "hkù", "Ìo\\d K´w, lM Ìlw\\w„"],
    [ 244, "hk", "Ìcw\\w (KwËew´ BZøwxb), xoRw„"],
    [ 245, "hkùn", "xgm ovLøw„"],
    [ 246, "hkú", "ÌeU h´w, AwKwl,"],
    [ 247, "hkú", "gwU, xg¬w, ¢Øi„"],
    [ 248, "hkún", "ex´Æw´ Ñp Ìjw\\w„"],
    [ 249, "hkút", "PPw, Ìiwp´w„"],
    [ 250, "hkú-ta", "P’Z iwp„"],
    [ 251, "hkunohkam", "´Rw, oiÞwU„"],
    [ 252, "hkùp", "ÌK^pw„"],
    [ 253, "hkùm", "m´y´, Ìbp„"],
    [ 254, "hkûm", "oóeÔYê, ÌMwU„"],
    [ 255, "hkuwat", "xLxrKy„"],
    [ 256, "hketrung", "Ìgtw Ìew\\w, NÙYw K´w„pwRw´„"],
    [ 257, "hken", "xpi, g´f„"],
    [ 258, "hkyèn", "pwxg KUw, ÑZtw´ Ìpw\\w„"],
    [ 259, "h", "Pyd RwxZ„"],
    [ 260, "hkyé", "Pyd Ìbm„"],
    [ 261, "hkyêng", "´Ow„"],
    [ 262, "hkyéng", "LwRdw„"],
    [ 263, "hkyét", "ÂKwB Ìjw\\w, ÂKwd„"],
    [ 264, "hkongrong", "KwVË´ gdw NåUy„"],
    [ 265, "hkòk", "ÌKwVw, VwB„"],
    [ 266, "hkòp", "i´i´, Awb´´„"],
    [ 267, "hkò", "GKiZ Ìpw\\w, oiôZ Ìp\\w„"],
    [ 268, "hkò", "ÂKwd, xM´w„"],
    [ 269, "hkôn", "Mwh´Ø ÌQw\\wly, Xlw„"],
    [ 270, "hkó", "KwË´v N´, ´wRcwdy„"],
    [ 271, "hkóhkam", "´Rw„"],
    [ 272, "hkón", "xbtw, AwMgswB xbtw, ex´ Ìjw\\w„"],
    [ 273, "hkomin", "pwlcy„"],
    [ 274, "hkóseng", "owiÞwRø„"],
    [ 275, "hkai", "Iliw, ´Ø\\w, xj p’ËlI, ÌMwËUB„"],
    [ 276, "hkaichyì", "ixY, iwlw, iÖK×Zw„"],
    [ 277, "hkaichyù", "xiQw iwQ„"],
    [ 278, "hkainu", "†icwd„"],
    [ 279, "hkaipyet", "pvo„"],
    [ 280, "hkaibam", "hÖl´ PwKdy„"],
    [ 281, "hkaiboksi", "hÖl„"],
    [ 282, "hkau", "AwËMwPw, Ìo\\d K´w, LÖlwly gw ÌRËV´y„"],
    [ 283, "hkauji", "LwDRy cwd„"],
    [ 284, "hkaubum", "cwd´__„"],
    [ 285, "hkautek", "AwÐL„"],
    [ 286, "hkau", "eaw´„"],
    [ 287, "hkaumun", "xeVw„"],
    [ 288, "hk", "ÌPwOw hwZ„"],
    [ 289, "hkaupuk", "g´w hwZ Aw´Ø xZl xiplwB ÑZtw´ K´w Gxgc xeVw„"],
    [ 290, "hkauyagu", "iw´ hwZ„"],
    [ 291, "hkausoi", "dÖWl„"],
    #[ 291, "hkausoi", "dÖWzl„"],
    [ 292, "hkaushóm", "ÌhwRd„"],
    [ 293, "hkojàk", "ÌKw´„"],
    [ 294, "hkoi", "Ìmn Ìpw\\w, AZyZ Ñp Ìjw\\w, máL„"],
    [ 295, "hkòi", "cw´Z Ìlw\\w gw xbtw„"],
    [ 296, "ga", "Mw^I„"],
    [ 297, "gà", "flw, eÙaK K´w gw Ìpw\\w„"],
    [ 298, "gâ", "xoPw, Ìgew´ K´w„"],
    [ 299, "gá", "hwnw, m²„"],
    [ 300, "gahkyi", "hxZRw„"],
    [ 301, "gahkyin", "HKøg¦ K´w„"],
    [ 302, "gahkau", "LÖlwly gw ÌRËV´y„"],
    [ 303, "gagá", "Awd, ÌgËlM„"],
    [ 304, "gagu", "Kwgw´ Ìepw„"],
    [ 305, "gàng", "Udw„"],
    [ 306, "gâng", "gøw® K´w, ÌMwUwB ´Lw„"],
    [ 307, "gáng", "fPzËfUz„"],
    [ 308, "gangà", "xplw, Pél Ìpw\\w„"],
    [ 309, "gangau", "hRw„"],
    [ 310, "gangong", "l´P´ K´w gw Ìpw\\w„"],
    [ 311, "gachy", "Kwgw´ ÌiwiwB„"],
    [ 312, "gachyùt", "Ìiwp´w, ÌiwPw„"],
    [ 313, "gachyút", "xgnw„"],
    [ 314, "gatsà", "lwxM c´w„"],
    [ 315, "gaja", "hwl, K×ml„"],
    [ 316, "gajai", "ÌKw\\w, eÞKwm K´w„"],
    [ 317, "gajam", "Ìciwly K´w„"],
    [ 318, "gaji", "Kwgw´ xeZwip„"],
    [ 319, "gaji gawoi", "xeZwip oKl, eÔgµêR oKl„"],
    [ 320, "gajidui", "Kwgw´ eÔgµê xeZwip„"],
    [ 321, "gajong", "PK ÌLw\\w„"],
    [ 322, "gatà", "gPw, xdYêt K´w„"],
    [ 323, "gatâ", "Ahw\\, dwBxKtw„"],
    [ 324, "gatá", "xhZ´Z, xhZ´„"],
    [ 325, "gatan", "Rxetw, Ifx´ e´w„"],
    [ 326, "gateng", "xPd xbtw, Bv´wRy´ bwxs„"],
    [ 327, "gatut", "lM Ìew\\w, owqwu Ìpw\\w„"],
    [ 328, "gatun", "PÖxU, Pwe´„"],
    [ 329, "gatong", "bÖU×K×´w K´w„"],
    [ 330, "gatóng", "xeQxl e´w„"],
    [ 331, "gahtâ", "Mwaw, KxgZw„"],
    [ 332, "gahtàp", "Rew, GUw´ Ie´Z GUw Ìaw\\w„"],
    [ 333, "gahtàn", "Kewl, hwMø„"],
    [ 334, "gahtân", "gRwly gwp„"],
    [ 335, "gahtam", "KUw„"],
    [ 336, "gahtí", "K"],
    [ 337, "gahting", "K____, ciyêt Duo\\„"],
    [ 338, "gahtum", "RiwK´w, ÌMwËUw\\w„"],
    [ 339, "gadáng", "gwMx´ e´w, gwM´w„"],
    [ 340, "gadap", "Rxetw, dPw„"],
    [ 341, "gadì", "ÌeÞi´ Depw´„"],
    [ 342, "gaduk", "xPT´-gwL´„"],
    [ 343, "gadup", "l´w, RM´w K´w„"],
    [ 344, "gadung", "Gxgc xZl xeVw, xmilÖ AwlÖ„"],
    [ 345, "gadun", "g¬w„"],
    [ 346, "gadé", "xKiwd, xK ex´iwY´„"],
    [ 347, "gadegà", "ÌKxd, ÌKwdfwËl„"],
    [ 348, "gadòn", "Rxetw, If´w„"],
    [ 349, "gadôn", "fx´v„"],
    [ 350, "gadai", "ÌKwd„"],
    [ 351, "gadau", "ÌgVwZ xPT´w„"],
    [ 352, "gadoi", "(ZwËiwl BZøwxb) KUw„"],
    [ 353, "ganâ", "gwËtK„"],
    [ 354, "ganang", "K’Z, KÐl„"],
    [ 355, "ganam", "Ìgw\\w´y„"],
    [ 356, "ganí", "Kwgw´ iwiyËtK„"],
    [ 357, "ganing", "ÌKËd, xKbË´„"],
    [ 358, "ganîng", "Kwgw´ dËg#„"],
    [ 359, "ganú", "iwK, KyU„"],
    [ 360, "ganú gawá", "xeZÙ-iwZÙ, Axhhw\\K„"],
    [ 361, "ganun", "N^pw„"],
    [ 362, "ganau", "Kwgw´ hwB gw hxd„"],
    [ 363, "ganoi", "AleËZ, ÌKËdgwËK„"],
    [ 364, "gapà", "K"],
    [ 365, "gapâng", "gwMx´ e´w„"],
    [ 366, "gaprip", "xRxlxK DVw„"],
    [ 367, "gaput", "XwxK ÌeËlw\\w, eÖxZ ÌeËlw\\w„"],
    [ 368, "gapó", "f×Uw gw f×ËUw\\w„"],
    [ 369, "gapòng", "xhZ´Z xgn DVw„"],
    [ 370, "gahpà", "Kwëb„"],
    [ 371, "gahpyui", "ÉÉx´ gRw gw iw´w„"],
    [ 372, "gabâ", "ÌoKw xbtw, M´i K´w„"],
    [ 373, "gabá", "xgmwl, WwO´„"],
    [ 374, "gabang", "ÌVlw-ÌpPw„"],
    [ 375, "gabyì", "g"],
    [ 376, "gabyí", "Gxgc MQ„"],
    [ 377, "gabrim", "xRxlKw, Ìewp´ xbtw„"],
    [ 378, "gabròng", "ÌKwlwpl K´w„"],
    [ 379, "gabù", "†xs K´w„"],
    [ 380, "gabú", "Awdëb Ìew\\w, oËìæwxnZ Ìpw\\w„"],
    [ 381, "gabui", "d"],
    [ 382, "gabun", "f×Pf×Pw, DB ÌewK„"],
    [ 383, "gabyé", "MPKw, hx´Ë´ i´w„"],
    [ 384, "gabai", "iw´w, ZøwM K´w„"],
    [ 385, "gabù", "†xs K´w„"],
    [ 386, "gabú", "oËìæwxnZ Ìpw\\w„"],
    [ 387, "gabó", "eÖd´ MVd K´w„"],
    [ 388, "gaboi", "xg¬w f×ËUw\\w„"],
    [ 389, "gamâ", "ÌKwd„"],
    [ 390, "gamang", "xPxUxK Ìjw\\w, xPxUKw„"],
    [ 391, "gamat", "ewdy xPxUKw„"],
    [ 392, "gaman", "Lwly, mÔdø„"],
    [ 393, "gamung", "Kaw, KËaweKad„"],
    [ 394, "gamù", "iÁ jÖ¦ K´w„"],
    [ 395, "gamut", "f×Kw, Rw´w„"],
    [ 396, "gamoi", "Kwgw´ Ìexp„"],
    [ 397, "gayà", "lwR K´w, lwR„"],
    [ 398, "gayâ", "LËRw\\w, AwPÖ´w„"],
    [ 399, "gayau", "xiplw, xipËlw\\w„"],
    [ 400, "gayoi", "LRxZ lMw„"],
    [ 401, "gara", "ÌKwdËUw, K’Z„"],
    [ 402, "garat", "dËg#„"],
    [ 403, "garan", "xgh£Ø K´w, hwM K´w„"],
    [ 404, "garap", "Ìcw^\\w Pwv„"],
    [ 405, "garì", "K^ew„"],
    [ 406, "garim", "c´w, AwUK K´w„"],
    [ 407, "garum", "lM xbtw, opwt K´w„"],
    [ 408, "garút", "N^pw„"],
    [ 409, "garót", "PÖP´w, Udw„"],
    [ 410, "galà", "flw, bÖfwl K´w„"],
    [ 411, "galá", "hw´Zyt„"],
    [ 412, "galàng", "Ggw´, ÌKxZtw gw„"],
    [ 413, "galâng", "CMl P´wB„"],
    [ 414, "galì", "iwlw xe¬w„"],
    [ 415, "galim", "xe´xe´w„"],
    [ 416, "galú", "byNl, l¹w„"],
    [ 417, "galung", "ÌKwilytw, ÌKwil„"],
    [ 418, "galun", "LÖPw„"],
    [ 419, "galup", "Qwl ÌPw\\w„"],
    [ 420, "galé", "xWlw„"],
    [ 421, "galep", "G"],
    [ 422, "galem", "f×Pf×PwB Kaw ÌKw\\w„"],
    [ 423, "galó", "Gdw, gËdw\\w, x¢Øtw eb„"],
    [ 424, "galau", "ZZwxlËK, AdxZelËi„"],
    [ 425, "galoi", "ÌKxZtw, ÌjxZtwI„"],
    [ 426, "gawà", "KwËiw´w, bþæ K´w„"],
    [ 427, "gawá", "Kwgw´ xeZÙ„"],
    [ 428, "gawan", "E´yqw K´w, o¬wd K´w„"],
    [ 429, "gawâm", "eÞxZcµxd Ìpw\\w„"],
    [ 430, "gawut", "f×Kw„"],
    [ 431, "gawoi", "Aep´Y K´w, Kwxs xdtw„"],
    [ 432, "gasup", "¢Øyrw K´w, ÌLlw„"],
    [ 433, "gashin", "Ìcw\\w„"],
    [ 434, "gàp", "oRw, xdiêwY K´w„"],
    [ 435, "gàm", "hwM K´w, xgh£ß K´w, gåUd K´w„"],
    [ 436, "gáp", "†xltw, †xl iw´w„"],
    [ 437, "ginhkà", "Aoiwd, ÌgËlM„"],
    [ 438, "ginjò", "ÌKë©þÿwd„"],
    [ 439, "gindun", "Ìjw´w xbtw„"],
    [ 440, "gindoi", "Pwxëb Ìjw\\w„"],
    [ 441, "ginrù", "Ìo\\d K´w, lMZ f×´w„"],
    [ 442, "ginlang", "xlŠ, †® AvM„"],
    [ 443, "ginwang", "xRlw gw ob´„"],
    [ 444, "ginsishang", "ÌKËKêUÖ\\w„"],
    [ 445, "ginsup", "ÌLl gw ÌLlw„"],
    [ 446, "ginsum", "UxON´„"],
    [ 447, "gyì", "pwDlw, NÖ´w„"],
    [ 448, "gyi-gò", "GKw-ÌgKw„"],
    [ 449, "gyí", "LÉ„"],
    [ 450, "gying", "DÒxZ Ìpw\\w, hwl„"],
    [ 451, "gyìng", "iwdxoK ,mx£Ø„"],
    [ 452, "gyit", "g¬w„"],
    [ 453, "gyin", "gdw, Duewbd K´w„"],
    [ 454, "grup", "ex´o´, ex´Ëgm„"],
    [ 455, "gyip", "xUxetw„"],
    [ 456, "gù", "PPw, PwxP ÌeËlw\\w„"],
    [ 457, "gú", "oóeÔYê„"],
    [ 458, "gui", "K×K×´„"],
    [ 459, "guigai", "Nx´twl„"],
    [ 460, "gui-", "iZw K×K×´, owpoy eÖ´Øn„"],
    [ 461, "gui-wî", "iwBKy K×K×´„"],
    [ 462, "gung", "†Y„"],
    [ 463, "gùn", "gÖKw„"],
    [ 464, "gunsu", "M´Ø„"],
    [ 465, "gup", "U×xe BZøwxb xe¬w„"],
    [ 466, "gup-chyop", "U×xe„"],
    [ 467, "gup-ban", "Rwxe„"],
    [ 468, "gùm", "pwDlw„"],
    [ 469, "gumgai", "gÙ¦w, gÖxs iwdÖp„"],
    [ 470, "gumkâ", "xP´wl„"],
    [ 471, "gumgyin", "xZt„"],
    [ 472, "gumchyai", "gwxl„"],
    [ 473, "gumdin", "ÌMwUw, NÖ´dytw gþç„"],
    [ 474, "gumpâ", "ÌgwKw„"],
    [ 475, "gumpak", "´Ow lwI„"],
    [ 476, "gumpup", "ÌgwKw„"],
    [ 477, "gumhpuhpum", "pwfËlw„"],
    [ 478, "gumaráng", "ÌNw^´w„"],
    [ 479, "gumròng", "Awr¹´„"],
    [ 480, "gumsau", "Z´iÔR„"],
    [ 481, "g", "KÚZšZw„"],
    [ 482, "gen", "g´f, xpi„"],
    [ 483, "gông", "ÌPËp´w, m´y´„"],
    [ 484, "gôm", "xPPw´ gwxU„"],
    [ 485, "gohkun", "DB ÌewK„"],
    [ 486, "gainu", "hwjêøw, eZîy„"],
    [ 487, "gau", "ÌLbw, AwMÐl Ìjw\\w„"],
    [ 488, "gaula-uk", "D^U„"],
    [ 489, "grau", "AxZx´£Ø, ÌgxQ„"],
    [ 490, "goi", "WwK xbtw„"],
    [ 491, "goiwát", "ÌRwldy, ?"],
    [ 492, "nga", "ÌKw\\w, eÞKwm K´w„"],
    [ 493, "ngà", "iwQ„"],
    [ 494, "ngâ", "i’p, ÌKw\\w„"],
    [ 495, "ng", "g"],
    [ 496, "ngá", "aKw, RytwB aKw, gwo K´w„"],
    [ 497, "ngai", "iB„"],
    [ 498, "ngàk", "hwx´„"],
    [ 499, "ngang", "Uwd, mKU„"],
    [ 500, "ngat", "hwxO Ìjw\\w„"],
    [ 501, "ngan", "Mwxl xbtw, iwdw K´w„"],
    [ 502, "ngap", "g¬ Ñp Ìjw\\w, g¬ K´w„"],
    [ 503, "ngam", "RÖVw, gwKy aKw„"],
    [ 504, "ngarai", "ewe, bÖûKiê„"],
    [ 505, "ngalong", "dOlw, Gxgc eqy„"],
    [ 506, "ng", "ÌmwKËmwKw„"],
    [ 507, "ngù", "ÌKwRw Ìpw\\w„"],
    [ 508, "ngau", "bi, mx£Ø„"],
    [ 509, "ngoi", "gRw gw gËRw\\w„"],
    [ 510, "chya", "odw, ´v xbtw„"],
    [ 511, "chyahkan", "ÌKK×´w„"],
    [ 512, "chyahkyi", "px´Y„"],
    [ 513, "chyahku", "Ìjwxd, þèy xlŠ„"],
    [ 514, "chyahk", "†b„"],
    [ 515, "chy", "pwlKw, hwx´ dp’t„"],
    [ 516, "chyangau", "K×xl P´wB„"],
    [ 517, "chyat", "Uwd K´w, gÖxR Ìew\\w„"],
    [ 518, "chyàn", "gPw, ex´Æw´ K´w„"],
    [ 519, "chyám", "ÌPÄw K´w, eÞtwo K´w„"],
    [ 520, "chyaran", "Pwldy„"],
    [ 521, "chyaru", "oÖ´w, ib„"],
    [ 522, "chyalu", "Ñp Ìjw\\w„"],
    [ 523, "chyaloi", "AxZ eÖ´Yy„ eÞL´ jÖM„"],
    [ 524, "chying", "Nwp„"],
    [ 525, "chyinghkang", "lwB„iÖlw„g¬w Kxg„"],
    [ 526, "chyinghkyi", "a"],
    [ 527, "chyingdu", "Nwpdy„"],
    [ 528, "chyingnam", "xZl„"],
    [ 529, "chyìng", "ÌXwl, PÖK, xZI\\w„"],
    [ 530, "chyù", "MwLy´, þæd„"],
    [ 531, "chyù", "Ñb MwLy´„"],
    [ 532, "chyù-si", "g"],
    [ 533, "chyú", "Iw¢, ÌK\\l„"],
    [ 534, "chyùng", "jÖ¦ De¢Øi„"],
    [ 535, "chyút", "IlwB Apw, IxlD\\w„"],
    [ 536, "chyun", "ex´Ëmwc K´w„"],
    [ 537, "chyúp", "Ìowxe ÌLw\\w„"],
    [ 538, "chyum", "gÖ´™y„"],
    [ 539, "chye", "Rdw„"],
    [ 540, "chéju", "KÚZšZw„"],
    [ 541, "chyai", "ÌLlw, Ìciwxl K´w„"],
    [ 542, "chyaumun", "Ìg#¦ xhq×„"],
    [ 543, "chyóp", "Rìç´ Qwl„"],
    [ 544, "choi", "xdiêl, exg¢„"],
    [ 545, "chyòng", "ixëb´, eÔRw-þÿl„iVwxcKw´y„"],
    [ 546, "chyông", "QwxZ„Q¢„"],
    [ 547, "tsà", "oÖ´w, ib„"],
    [ 548, "t", "ÌgMy, bÙs gwËg xPìæw K´w„"],
    [ 549, "tsâ", "m, mZK„"],
    [ 550, "tsâng", "ewZl, pwlKw„"],
    [ 551, "tsân", "bÖ´, bÖ´dy„"],
    [ 552, "tsàp", "hwlÖK, xat Ìpw\\w„"],
    [ 553, "tsàm", "UxO Rwl„"],
    [ 554, "tsì", "Jnc, bw\\wt„"],
    [ 555, "tsit", "ÌoDRytw„"],
    [ 556, "ja", "gwË´ gwË´ Apw Ìjw\\w K´w„"],
    [ 557, "jà", "Uwd, KUKxUtw, ewdy ZÖlw„"],
    [ 558, "jàt", "U×K×´w K´w, jwxP xbtw gw Ìlw\\w„"],
    [ 559, "já", "ÌowY„"],
    [ 560, "já dup", "Ìowdw´y„"],
    [ 561, "ját", "Rdô, RwZK, dwUK„"],
    [ 562, "jàn", "Awixd lMw, gwKy aKw, hwjøêw„"],
    [ 563, "jân", "oÔjøê„oÔËjêøwbt, eÔg„exúPi,Ìgxl iw´ Ìjw\\w„bÖe´ytw„oÔjøwêþæ„"],
    [ 564, "jahkring", "´LwB xbtw, ´¥ K´w„"],
    [ 565, "jahkrú", "9, d ovLøw„"],
    [ 566, "jang", "BxZiËcø, jxb„"],
    [ 567, "jap", "Ròlw„"],
    [ 568, "japâ", "ÌgRw´, xPìæw„"],
    [ 569, "jahpá", "ewZl K´w„"],
    [ 570, "jahpan", "G?"],
    [ 571, "jahpû", "ÌMlw gw ePw„"],
    [ 572, "jahpoi", "xdëbw K´w, xgÌgPdw K´w„"],
    [ 573, "jamjau", "KÄ, bÖL ÌhwMw„"],
    [ 574, "jamna", "beêY, Abdw„"],
    [ 575, "jik", "Awcw Ìiwd„"],
    [ 576, "jing", "DÒZ Ìpw\\w, DVw„"],
    [ 577, "jinglam", "Â´„"],
    [ 578, "jingmut", "m´y´´ ZËlw\\w Avm´ ÌKm„"],
    [ 579, "jit", "iÖ¢w, iÖZ„"],
    [ 580, "jin", "Këbw„"],
    [ 581, "jinlông", "§ye„"],
    [ 582, "jip", "G"],
    [ 583, "jim", "xd´\\, xdiwZ„"],
    [ 584, "ju", "ÌRw´ Rg´ K´w„"],
    [ 585, "jút", "PÖK„"],
    [ 586, "judai", "dwx´„"],
    [ 587, "jùn", "ÌewUw, lËMw\\w„"],
    [ 588, "jum", "c´w gw PÖ\\w„"],
    [ 589, "jùm", "xdiL, ÌlwY„"],
    [ 590, "jumgang", "Kwlw xdiL„"],
    [ 591, "jùm", "icÔËip„"],
    [ 592, "jû", "KwBU„"],
    [ 593, "jú", "Rlw gweÖ´w„"],
    [ 594, "jút", "PÖK„"],
    [ 595, "jê", "KwMR„"],
    [ 596, "jêlap", "KwMR„"],
    [ 597, "jé", "flw, xZZw, bÖhwM K´w„"],
    [ 598, "jai", "PZfUw„"],
    [ 599, "jaiwa", "xPvËf# oKl´ Gxgc MyxZKw„"],
    [ 600, "jau", "AwË´wpY K´w, DVw„"],
    [ 601, "jau-jau", "ZZwxlËK, ÌowdKwËl„"],
    [ 602, "jàu", "cx´ Ìlw\\w, awe iw´w, xhq×, eÖË´wxpZ„"],
    [ 603, "jaukut", "Piê Ì´wM„"],
    [ 604, "jauké", "Z´ØY gtÆ xhq×„"],
    [ 605, "jaushang", "mÞiY„"],
    [ 606, "joi", "Ìo´, xKËlw„"],
    [ 607, "jot", "IlwB Ìjw\\w, IlB e´w„"],
    [ 608, "jô", "DuKÚÄ, hwl„"],
    [ 609, "jôm", "ÌLbw gw ÌLbwB eËVw\\w„"],
    [ 610, "ñâng", "xgn„"],
    [ 611, "ñan", "gÖx¦, šwd, eÞšw„"],
    [ 612, "ñap", "g"],
    [ 613, "ñét", "eÞZøwpw´ K´w„"],
    [ 614, "tama", "Zwiw„"],
    [ 615, "tara", "dyxZ, AwBd, KwdÖd"],
    [ 616, "tà", "xdxQdw, xil ÌLw\\w, ÌPËlKw„"],
    [ 617, "tâ", "iwp, Kwl„myZ Kwl„MÞyûi Kwl„gwx´nw gw Ìpiìæ Kwl„m´u Kwl„"],
    [ 618, "tàng", "DPMêw K´w, ebgyZ gËpw\\w, ÌgwRw DËVw\\w, xPvËf# ex´twl´ eãi eÖ¢„"],
    [ 619, "tàt", "Gx´ xbtw, ZøwM K´w„"],
    [ 620, "tàn", "hwxO Ìjw\\w„"],
    [ 621, "tàm", "MËgnYw K´w, xgQ´w„"],
    [ 622, "tàmhpyit", "b¬„"],
    [ 623, "tâm", "b¬„"],
    [ 624, "talau", "gÞÊeÖ¢ dby„"],
    [ 625, "ták", "AdÖiwd K´w, hwxg ÌPw\\w, oËëbp K´w„"],
    [ 626, "ting", "ogµê, iÔV, oiMÞ„"],
    [ 627, "tingkak", "KxUtw„"],
    [ 628, "tingkok", "Lwl„"],
    [ 629, "tinghkung", "gþè, owR„"],
    [ 630, "tinghtàn", "Pv¢ØiY K´w„"],
    [ 631, "tinghtá", "ogµê¢,ogµê gøwey„"],
    [ 632, "tingnang", "Ètv, šwxZ, K×U×¹„"],
    [ 633, "tingret", "g"],
    [ 634, "tì", "WwBdy lMw„"],
    [ 635, "ting", "ÌMwËUB VwBZ„owgµêRdyd„"],
    [ 636, "tinghtáng", "jËZ ZËZ, oiþæ„"],
    [ 637, "tìn", "ÌgËMË´ ÌLwR Kwsw„"],
    [ 638, "tinyang", "PKy, Awod„"],
    [ 639, "tiri", "mÙŠ„"],
    [ 640, "tung", "IePw, IÐhdby Ìpw\\w„"],
    [ 641, "tùn", "xZI\\w, xZtwB ÌKwil K´w„"],
    [ 642, "túp", "hx£ê, oóeÔYê„"],
    [ 643, "tùm", "†xU, gyR„"],
    [ 644, "túm", "Uöi„"],
    [ 645, "tú", "MRw„"],
    [ 646, "tu-û", "i´w m xdtw Kxfd„"],
    [ 647, "tén", "xo^P´w, jËZ ZËZ ´Lw„"],
    [ 648, "tép", "ÌPew gw ÌPxe c´w„"],
    [ 649, "t", "xdiwZ, xd:m²„"],
    [ 650, "tong", "UÖK×´w„"],
    [ 651, "tongban", "xidxZ K´w, AdÖË´wc K´w„"],
    [ 652, "tonglong", "ÌMwËUB, ogµê¢„"],
    [ 653, "toléng", "gM´wB xbtw, gwM´w„"],
    [ 654, "tò", "Ahw\\, AwKwl„"],
    [ 655, "t", "ZwP f×Ugl BZøwxb ÌLlw„"],
    [ 656, "tòng", "jËVÄ, RÖ´w„"],
    [ 657, "tòt", "ew´ Ìpw\\w, ÌbD xbtw„"],
    [ 658, "tòn", "Ìaw\\w, ´Lw„"],
    [ 659, "tòm", "Ìmn Ìpw\\w, oóeÔYê Ìp\\w„"],
    [ 660, "tông", "gwM´w, Â\\w„"],
    [ 661, "tai", "Ìpw\\w, D£´ xbtw„"],
    [ 662, "taihpót", "IË´ xdmw„"],
    [ 663, "taukû", "gwi KwQ„"],
    [ 664, "taubyen", "ewdy KwQ„"],
    [ 665, "htamun", "U×Ëowdw„"],
    [ 666, "h", "ZÖxl Ìlw\\w, xgcgw xgtw K´w„"],
    [ 667, "h", "dwOl, D£´ xbtw„"],
    [ 668, "h", "xPMw„"],
    [ 669, "h", "NÖx´ Apw gw Ìjw\\w, Rgwg xbtw„"],
    [ 670, "h", "Mwxl xbtw, Mwxl ew´w„"],
    [ 671, "h", "WwV„"],
    [ 672, "h", "AËPZd Ìpw\\w„"],
    [ 673, "h", "Rew, ÌPwKw„"],
    [ 674, "h", "eÖË´wxpZ ZøwM K´w„"],
    [ 675, "h", "ÌPwZwl„"],
    [ 676, "htát", "KwiZ lMw, Aw\\møK„"],
    [ 677, "h", "Zwl MQ„"],
    [ 678, "h", "jËVÄ„"],
    [ 679, "h", "Gpw, iwxUZ gpw„"],
    [ 680, "h", "WÔg ÌLw\\w„"],
    [ 681, "h", "Aw¢ØiY K´w„"],
    [ 682, "h", "esw, ewV K´w, MdYw K´w„"],
    [ 683, "h", "g´nÖY e´w, xPvËf# ex´twl´ PZÖaê bÖxpZw„"],
    [ 684, "h", "NÖPw iw´w„"],
    [ 685, "h", "DeËjwMø, DxPZ„"],
    [ 686, "h", "ÌoËiKw„"],
    [ 687, "h", "gwKP, Ìawew„"],
    [ 688, "h", "Aìæ Ìpw\\w, Ìmn Ìp\\w„"],
    [ 689, "hté", "lMZ, ÑoËZ„"],
    [ 690, "h", "g¬ K´w„"],
    [ 691, "h", "Aw¢ØiY K´w, RM´w K´w„"],
    [ 692, "h", "Lg´ xbtw„"],
    [ 693, "h", "Ìgtw Ìpw\\w, dÄ Ìpw\\w„"],
    [ 694, "h", "Ìewp´, A¬Kw´ dpt„"],
    [ 695, "htòk", "iÔløwcw´ xbtw„"],
    [ 696, "h", "gblw, DxV Ìjw\\w„"],
    [ 697, "h", "Ìo#\\w„"],
    [ 698, "h", "ÌoBËUw„"],
    [ 699, "h", "PÖ\\w, ÌXwl„"],
    [ 700, "h", "ÌRl, ´OwN´„"],
    [ 701, "da", "Ìaw\\w, ZøwM K´w„"],
    [ 702, "dakasu", "xgmò xgbøwlt„"],
    [ 703, "dagâ", "KxVtw, eÖxl, bwtK„"],
    [ 704, "dazik", "G?"],
    [ 705, "dabang", "h´xZ, ÌVlw-ÌpPw„"],
    [ 706, "d", "g?"],
    [ 707, "dabé", "xmnø„"],
    [ 708, "damà", "ÌRËV´y eq„"],
    [ 709, "damâ", "ÌKwd„"],
    [ 710, "damyà", "WKwBU, WwK×„"],
    [ 711, "dará", "eÞ\\Pdw, ciê„"],
    [ 712, "dagàng", "NÖx´ f×´w„"],
    [ 713, "dagup", "XwKw„"],
    [ 714, "dating", "gËlË´, glpZKwË´„"],
    [ 715, "dà", "ZwZ Ìgw\\w, ZwZ„"],
    [ 716, "dàlang", "ZwZ´ mwl„"],
    [ 717, "dàt", "Gx´ xbtw, iÖ£Ø K´w, cwZÖ, xgRÖly„"],
    [ 718, "dàn", "KUw, xdYêêtK´w, ipw§ye„"],
    [ 719, "danhpòn", "Ifx´ Ìjw\\w„"],
    [ 720, "dán", "KKêU Ì´wM„"],
    [ 721, "dàp", "QwB, xghwM, iìèwlt„"],
    [ 722, "dàpkóp", "RÖmwl„"],
    [ 723, "dàm", "Awpl gpl„"],
    [ 724, "dâm", "f×´w„"],
    [ 725, "dì", "xPOw,ÌRw´w xbtw,gËZw\\wgwP´Ø„"],
    [ 726, "dik", "jËVÄ„"],
    [ 727, "ding", "xPcw, Ìewd„"],
    [ 728, "dinghkû", "N´, ex´gw´„"],
    [ 729, "dinggum", "G"],
    [ 730, "ding", "gÖxs iwdÖp„"],
    [ 731, "dinggò", "N´ gw goxZ´ þÿwd„"],
    [ 732, "dinggó", "UËK#„"],
    [ 733, "dinggóng", "N´, ex´twl„"],
    [ 734, "dingdà", "bxqY„"],
    [ 735, "dingding", "ÌewËd ÌewËd, FRÖÐK„"],
    [ 736, "dingdung", "D£´„"],
    [ 737, "dingyam", "AwV× Kwsw„"],
    [ 738, "dingyeng", "Z´w MQ„Z´w MwRly„"],
    [ 739, "dingla", "gÙ¦eÖ´Øn„"],
    [ 740, "dingshi", "NåUy„"],
    [ 741, "dit", "UKx´tw, ÌVlw„"],
    [ 742, "din", "NÖ´dytw, xgh£ØÌpw\\ww„"],
    [ 743, "dip", "Qew, eÞKwm K´w„"],
    [ 744, "dim", "ÌhUw xbtw„"],
    [ 745, "dìm", "xPvËf# ex´twl´ dgi Kdøw„"],
    [ 746, "du", "xPvËf# ex´twl´ PZÖaê eÖ¢„"],
    [ 747, "dui", "xiVw, AwBZw„"],
    [ 748, "duhkà", "bÖ:L, Ìgbdw„"],
    [ 749, "dung", "gpw„"],
    [ 750, "dun", "Udw, Uwxd Ñl Ìjw\\w, Ms„"],
    [ 751, "dum", "Mi Ìew\\w, idZ e´w, eÙxa\\y„"],
    [ 752, "dumbau", "Ms„"],
    [ 753, "dumbra", "xgQw„"],
    [ 754, "dumsi", "x¢m, 30,  ÌKËUlw eÂ„"],
    [ 755, "dumsikoi", "ÌKËUlw eÂ´ KwBU„"],
    [ 756, "dù", "xWxO„"],
    [ 757, "dù-bòng", "xWxO f×lw, MlM¡„"],
    [ 758, "dùm", "gRw gw gËRw\\w„"],
    [ 759, "dû", "iÖ´gy, ÌdZw„"],
    [ 760, "dú", "Awxp Ìew\\w, DexþÿZ Ìpw\\w„"],
    [ 761, "de", "xdiêwY K´w, eÞxZþÿwed K´w„"],
    [ 762, "degà", "ÌKxd, ÌKwdfwËl„"],
    [ 763, "dégoi", "K’Z, ÌKwd VBZ„"],
    [ 764, "de", "ÌKwdfwËl„"],
    [ 765, "dè", "fwËl, Ñl„"],
    [ 766, "d", "gwKP, P«ÖK„"],
    [ 767, "deng", "owpo K´w, iwBl„"],
    [ 768, "dêng", "ÌoB oitZ„"],
    [ 769, "d", "WÖxK Ìew\\w„"],
    [ 770, "d", "fËUw iw´w„"],
    [ 771, "dén", "Ì´wM xgtew„"],
    [ 772, "d", "ÌKwdËUw„"],
    [ 773, "dò", "hOw„"],
    [ 774, "dó", "oiôwd K´w, ´wxL xbtw„"],
    [ 775, "dông", "ÌbxLg ew´w, bÙmøit„"],
    [ 776, "d", "†xs K´w„"],
    [ 777, "dòn", "Rxetw, Re iw´w„"],
    [ 778, "dôn", "LwxP K´w„"],
    [ 779, "dôm", "ZøwM K´w, AwZx´ Ìjw\\w„"],
    [ 780, "dósa", "Ì§n, Ì¢Øwc„"],
    [ 781, "dai", "ÌoB„"],
    [ 782, "dài", "ÌPwKw„"],
    [ 783, "dainà", "AwxR xdmw„"],
    [ 784, "dainì", "AwxR„"],
    [ 785, "daihpót", "DË´ xdmw„"],
    [ 786, "dau", "lwxM c´w, Iliw„"],
    [ 787, "doi", "lwLÖxU Ñl ÌLwR Kwsw, xPvËf# ex´twl´ ZÙZyt eÖ¢„"],
    [ 788, "n’", "i´i K´w, btw K´w„"],
    [ 789, "n’", "PwDl„"],
    [ 790, "ntsin", "ewdy„"],
    [ 791, "njò", "ÌLwew„"],
    [ 792, "ntá", "MÙp, N´„"],
    [ 793, "nhtang", "IlZwÐK„"],
    [ 794, "ndà", "eVwxl„"],
    [ 795, "ndung", "byNl„"],
    [ 796, "ndun", "AxZxa ÌKwVw„"],
    [ 797, "npan", "xeQ ÌPwZwl„"],
    [ 798, "npyik", "RlKytw„"],
    [ 799, "npu", "Zl„"],
    [ 800, "nhpát", "gxi K´w„"],
    [ 801, "nbang", "AwM ÌPwZwl„"],
    [ 802, "nbâ", "gþè, KwËew´„"],
    [ 803, "nbung", "gwtÖ, gZwp„"],
    [ 804, "nrâng", "pwr„"],
    [ 805, "nlî", "gyR„"],
    [ 806, "nlung", "Ìd#, dZÖd„"],
    [ 807, "na", "ÌZwiw´„"],
    #[ 807, "na", "ÌzZwiw´„"],
    [ 808, "nagá", "iK´„"],
    [ 809, "najing", "gÉZ, AxcK„"],
    [ 810, "nai", "KQ× gw AwlÖ, eËKw\\w„"],
    [ 811, "nairí", "eËKw\\w oÖZw„"],
    [ 812, "nadan", "LÖlw VwB, eaw´„"],
    [ 813, "nadí", "dwK„"],
    [ 814, "nadu", "Rdi´ e´wB KwY Klw„"],
    [ 815, "nan", "gwU ÌbLÖ\\w, e´w„"],
    [ 816, "nanhtèng", "ÌZwiwËlwK, AwËewdwËlwK„"],
    [ 817, "namau", "gwi eaw´„"],
    [ 818, "namrì", "xdt´, ZÖnw´„"],
    [ 819, "nà", "dwewt, AK×ml„"],
    [ 820, "nâ", "KwY„"],
    [ 821, "ná", "eaw´, ÌbB„"],
    [ 822, "nàk", "hwx´„"],
    [ 823, "nàt", "ÌbgZw, RlwB xbtw„"],
    [ 824, "nàn", "eÖd´ K´w„"],
    [ 825, "nàm", "pwxg, RŠl„"],
    [ 826, "nàm", "Ndy RŠl„"],
    [ 827, "nàmta", "iPlw„"],
    [ 828, "nâgong", "AK´w, iÔLê„"],
    [ 829, "nâng", "Âdw, mÞ\\Y K´w„"],
    [ 830, "nâpen", "d"],
    [ 831, "nâhpang", "Klw, Ñg´w„"],
    [ 832, "nâbup", "iÔLê„"],
    [ 833, "nâbyeng", "ÌRwK„"],
    [ 834, "nâbai", "iÔLê, ewMl„"],
    [ 835, "naman", "Lwbø ÌZl„"],
    [ 836, "namyin", "ÌK´wxPd ÌZl„"],
    [ 837, "nari", "Nry, oit„"],
    [ 838, "nì", "Zw´yL, xbd„"],
    [ 839, "ní", "IP´„"],
    [ 840, "nî", "iwiy, ÌZwiwËlwK„"],
    [ 841, "nîhténg", "ÌZwiwËlwK„"],
    # [ 841, "nîhténg", "ÌzwiwËlwK„"],
    [ 842, "ning", "gQ´, gnê„"],
    [ 843, "nìng", "GËdB, xgdw Kw´Y„"],
    [ 844, "ningkyin", "Mwd, MyZ, ÌMw\\w„"],
    [ 845, "ninghkrin", "xgËmnš„"],
    [ 846, "ninghkyi", "KUw´y„"],
    [ 847, "ninghkû", "dwl„"],
    [ 848, "ninggâng", "fwK„"],
    [ 849, "ninggam", "M´w, RLlw´ Lwe„"],
    [ 850, "ninggyi", "Rp´w„"],
    [ 851, "ninggun", "gl, mx£Ø„"],
    [ 852, "ninggup", "iÖL„"],
    [ 853, "ninggyet", "Mwxl ew´w„"],
    [ 854, "ninggrau", "pËl# gwëb´„"],
    [ 855, "ningti", "R’„"],
    [ 856, "ningtén", "IV„"],
    [ 857, "ninghtû", "bw„"],
    [ 858, "ninghtoi", "xbd,Zw´yL„"],
    [ 859, "ningdim", "xeQ„"],
    [ 860, "ningdung", "AwM, DâP„"],
    [ 861, "ningnân", "dZÖd„"],
    [ 862, "ningnî", "Ww\\´, ÌiN„"],
    [ 863, "ningpót", "†x´, ÌoÞwZ, Aw´ºYy„"],
    [ 864, "ningri", "jwxV„"],
    [ 865, "ningwâ", "K×Vw´„"],
    [ 866, "ningsi", "KUw´y„"],
    [ 867, "ningsau", "KwxP„"],
    [ 868, "nin", "LÖPw, ÌVlw, ÌpPw„"],
    [ 869, "nu", "xWlw„"],
    [ 870, "nù", "xipËlw\\w, iMR„"],
    [ 871, "nùn", "o´Ø„"],
    [ 872, "nú", "iwZÙ„"],
    [ 873, "núdoi", "iwpy iwK„"],
    [ 874, "nútung", "AwewËbD„"],
    [ 875, "núshi", "o´Ø iwpy„"],
    [ 876, "netòk", "Â¢Ø cwZÖ, gyR„"],
    [ 877, "nè", "ovoMê K´w„"],
    [ 878, "nò", "Ìo\\w Kwsw, eÞYwi K´w„"],
    [ 879, "nó", "GVw„"],
    [ 880, "nòn", "xgmòwo K´w, iwxd Ìlw\\w„"],
    [ 881, "nòng", "jwxP xbtw, ÌVlw iw´w, PlËZ„"],
    [ 882, "nông", "xgl„"],
    [ 883, "nóng", "xPvËf# ex´twl´ x§Zyt eÖ¢„"],
    [ 884, "nau", "AxcK, ÌgxQ„"],
    [ 885, "noi", "IliwB ´Lw, fl lMw„"],
    [ 886, "pa", "oiwd, eaw´„"],
    [ 887, "p", "Ìgxb„"],
    [ 888, "panglai hkà", "owM´, oiÖ©„"],
    [ 889, "pahkí", "Lwxp cwd„"],
    [ 890, "Patkai bùm", "ewUKwB ewpw´„"],
    [ 891, "panau", "ÂKxU„"],
    [ 892, "palá", "Kwr, †xl„"],
    [ 893, "Palì", "ewxl hwnw„"],
    [ 894, "palí", "UOwl„"],
    [ 895, "palin", "gUl„"],
    [ 896, "palong", "ÌPwlw„"],
    [ 897, "pà", "diw, gpw„"],
    [ 898, "páng", "xdiìèY K´w, Ìjw´„"],
    [ 899, "páng laikâ", "xdiìèY e¢„"],
    [ 900, "pàt", "Gxgc KwYf×xl„"],
    [ 901, "pàn", "F×l, eÖûe„"],
    [ 902, "pamun", "gwRy iwBKy„"],
    [ 903, "parami", "ew´xiZw„"],
    [ 904, "parik", "ex´¢wY„"],
    [ 905, "prâ", "xgtew, g¦êd Ìpw\\w„"],
    [ 906, "prát", "gto, jÖM„"],
    [ 907, "palamla", "exLlw„"],
    [ 908, "pasî", "Kewp„"],
    [ 909, "pashí", "fxd„"],
    [ 910, "pí", "gwpy„"],
    [ 911, "ping", "Lx´KwZ xbtw„"],
    [ 912, "piman", "Ìeew„"],
    [ 913, "pishôn", "gwpy„"],
    [ 914, "pyî", "xPvËf# ex´twl´ o®i Kdøw„"],
    [ 915, "pyí", "xlewÌLw\\w, gw„"],
    [ 916, "pung", "owcÖ Kaw„"],
    [ 917, "punghkong", "ÌP\\w P´Ø„"],
    [ 918, "punghkò", "UÖp †xs„"],
    [ 919, "punghkau", "?g"],
    [ 920, "pù", "fÖl, ÌeU×„"],
    [ 921, "pûhkam", "eL´w owe„"],
    [ 922, "pûhkó", "ÌfxU owe„"],
    [ 923, "pút", "IZlw„"],
    [ 924, "p", "bÖiÖLytw owe„"],
    [ 925, "pûnoi", "ARMr„"],
    [ 926, "púp", "PÖiw ÌLw\\w„"],
    [ 927, "pûpok", "Ì´# iwQ„"],
    [ 928, "pupót", "†B„"],
    [ 929, "poi", "Ìilw, Duo\\„"],
    [ 930, "poi wáng", "Ìilw eaw´„"],
    [ 931, "pòt", "WÖxK Ìew\\w,jËVÄ„"],
    [ 932, "pôn", "pwZZ Ìlw\\w„"],
    [ 933, "hpa", "xK?"],
    [ 934, "h", "KwëbZ gÖxK xdtw„"],
    [ 935, "hpagâ", "Ìgpw, Ìgwew´„"],
    [ 936, "hpaji", "xmqw, Acøtd„"],
    [ 937, "hpà", "iw´ hwZ„"],
    [ 938, "h", "xdxQdw, bË´„"],
    [ 939, "hpá", "ewZl„"],
    [ 940, "hpài", "ZwP„"],
    [ 941, "hpang", "Aw´º K´w„"],
    [ 942, "hpàng", "xeQZ, A\\ËmnZ„"],
    [ 943, "hpàt", "iw´w, esw„"],
    [ 944, "hpàn", "RwxZ, gMê„"],
    [ 945, "hpân", "Awxmgµwêb xbtw„"],
    [ 946, "hpàm", "Nw, f´w„"],
    [ 947, "hpayà", "PPw„"],
    [ 948, "hpayau", "AxcK, ÌgxQ„"],
    [ 949, "hprá", "hMgwd gÖ¦„"],
    [ 950, "hpring", "h´w,oóeÔYê„"],
    [ 951, "hproi", "MyxZKwË´ eÞmvow K´w„"],
    [ 952, "hprong", "elwB Ìjw\\w, xeQ ÉÉKw„"],
    [ 953, "hprót", "Awxp Ìew\\w, IlwB xbtw„"],
    [ 954, "hprom", "xipËlw\\w, lMZ g¬w„"],
    [ 955, "hpalap", "Pw„"],
    [ 956, "hpalò", "gwpË´ gdw Kwe„"],
    [ 957, "hpyì", "Qwl, Piê„"],
    [ 958, "hpyî", "hÔZ„"],
    [ 959, "hpyí", "ÌLwRw, AdÖË´wc K´w„"],
    [ 960, "hpyìn", "iwvo BZøwxb KUw„"],
    [ 961, "hpù/hprù", "ÌMwU ÌLw\\w, Riw Ìpw\\w„"],
    [ 962, "hpung", "ÌmwU, eÞwxaê„"],
    [ 963, "hpúng", "LøwxZ„"],
    [ 964, "hpùn", "xe¬w, MQ„"],
    [ 965, "hpû", "Mw-cd, ePw„"],
    [ 966, "hpú", "KKwB, hwZÙ, ÌRwKwsw„"],
    [ 967, "hpùm", "owgxZ c´w, owgxZ Ìlw\\w„"],
    [ 968, "hpûm", "mKU„"],
    [ 969, "hpengbà", "ÌRwËlwOw„"],
    [ 970, "hpyé", "Awx´ Ìlw\\w„"],
    [ 971, "hóng", "oËZ, lMZ„"],
    [ 972, "h", "P"],
    [ 973, "hpò", "ÌLw\\w, Ìilw„"],
    [ 974, "hpót", "hx\\nøu„"],
    [ 975, "hpyau", "ÌgxQ, AwxcK„"],
    [ 976, "ba", "i´i ÌbLÖ\\w, gwB„"],
    [ 977, "bà", "ÌgwËKwPw K´w, Mhê\\Zy Ìpw\\w„"],
    [ 978, "bá", "hwM´ lMw„"],
    [ 979, "bakâ", "PÖx´tw„"],
    [ 980, "bakang", "Pë©Zwe„"],
    [ 981, "bang", "hË´w\\w, ÌhwU xbtw„"],
    [ 982, "bat", "gxpÆw´ K´w„"],
    [ 983, "b", "M¬„"],
    [ 984, "batót", "PÖxU gþè„"],
    [ 985, "bàn", "A\\Ë´wc K´w„"],
    [ 986, "banep", "xgQdw Pwb´„"],
    [ 987, "bapai", "Pwb´„"],
    [ 988, "bahpùn", "K¹l„"],
    [ 989, "babù", "ÌeåU„"],
    [ 990, "bàm", "ÌoËiKy Ìjw\\w„"],
    [ 991, "baman", "KwËew´ Ìilw ´xQ„"],
    [ 992, "byî", "†xP Ìjw\\w, elwB Ìjw\\w„"],
    [ 993, "byin", "Ìpw\\w„"],
    [ 994, "bu", "Mw^I„"],
    [ 995, "b", "glw,opwt K´w„"],
    [ 996, "bunghpoi", "NÖ´yYtw gZwp„"],
    [ 997, "bungli", "Kwi, Kiê, KZêgø„"],
    [ 998, "bù", "xe¬w„"],
    [ 999, "bùn", "xoxPKw„"],
    [1000, "bùp", "AK´w, iÔLê„"],
    [1001, "bùm", "egµêZ, ewpw´„"],
    [1002, "bûm", "f×lw (Mw BZøwxb)„"],
    [1003, "b", "Mxl Ìjw\\w„"],
    [1004, "byè", "MQKw„"],
    [1005, "byètchyi", "KÚeY„"],
    [1006, "byét", "ÌewK„"],
    [1007, "byoi", "Mxl Ìjw\\w„"],
    [1008, "bòng", "hwM K´w, lMËZ gø\\pw´ K´w„"],
    [1009, "bòng", "BRËd xoRdK opwt K´w„"],
    [1010, "bông", "xmnê, iÔ´„"],
    [1011, "bông", "lwIËLwlw„"],
    [1012, "b", "Zew iwdÖp„"],
    [1013, "bông", "Mw´Ø„"],
    [1014, "bônghpoi", "?"],
    [1015, "bông", "ZwËlw„"],
    [1016, "bai", "NÖx´ Apw gw Ìjw\\w, AwËK#„"],
    [1017, "bainam", "QwMly„"],
    [1018, "ma", "hx\\nøu Kwl gÖËRw\\w GK DeoMê;ÌjËd:- ‘g’ Awxpg, AwxdgBZøwxb„"],
    [1019, "ma-ut", "xMlw, xMxl ÌeËlw\\w„"],
    [1020, "ma-un", "dwx´Kl„"],
    [1021, "ma-um", "PÖxe ÌLw\\w„"],
    [1022, "m", "?, AwL´, ´wxmfl, lMí„"],
    [1023, "m", "M"],
    [1024, "m", "iÖVw„"],
    [1025, "m", "ov´qY K´w„"],
    [1026, "makyet", "ÌPwËgw\\w„"],
    [1027, "m", "K’hw´, ´qw K´w„"],
    [1028, "m", "ÌUwËewlw, g¬w„"],
    [1029, "mahká", "LÖlw, AwPx´Z Ìpw\\w„"],
    [1030, "mahkák", "ÌLKw´„"],
    [1031, "m", "Aw^PÖ´w„"],
    [1032, "mahkret", "AKw„"],
    [1033, "m", "KŸ, cµxd„"],
    [1034, "m", "ÌKw\\ly„"],
    [1035, "m", "owxP ´Lw„"],
    [1036, "m", "MyZ gw Mwd„"],
    [1037, "m", "Mwh´Ø ÌQw\\wly„"],
    [1038, "mahkó si", "gM´y„"],
    [1039, "mahkai", "owËKw, ÌoZÖ„"],
    [1040, "mahkài", "Awxs Ìaw\\w, IRU ÌLw\\w„"],
    [1041, "mahkau", "Awi´ly„"],
    [1042, "m", "PÖ\\w gw c´w„"],
    [1043, "m", "XwxK ´Lw, XwKdy„"],
    [1044, "m", "ibw´„"],
    [1045, "m", "ÌdZw, iÖLytw„"],
    [1046, "m", "Gxgc MQ„"],
    [1047, "m", "Ìg^Kw, xPcw dp’t„"],
    [1048, "magyî", "D´Ø, xUKw„"],
    [1049, "m", "hw´„"],
    [1050, "m", "xgxhÒ, xgxgc„"],
    [1051, "m", "GVytw„"],
    [1052, "m", "Ìg^Kw K´w„"],
    [1053, "magó si", "AwËel„"],
    [1054, "m", "Riw K´w, ÌMwËUw\\w„"],
    [1055, "m", "fPl Riw K´w„"],
    [1056, "machyì", "ÌgVw, Ìgiw´ e´w„"],
    [1057, "machyìng", "þi´Y, idZ e´w„"],
    [1058, "majing", "AwPl, oZø„"],
    [1059, "majim", "ÌK^pw ÌK^pw lMw„"],
    [1060, "m", "ÌmnK´w, Aìæ K´w„"],
    [1061, "m", "xdQw c´w„?"],
    [1062, "m", "M¬ Ìew\\w„"],
    [1063, "m", "xoPx´ Ìjw\\w„"],
    [1064, "m", "iÙZ Ìbp, i´w m„"],
    [1065, "m", "Aweb, KÄ„"],
    [1066, "m", "Ea Ìp´Ø\\w„"],
    [1067, "m", "Ìew\\wly,l’´w„"],
    [1068, "m", "iwdÖp, iwd\\„"],
    [1069, "m", "Gxgc ewZ iPlw„"],
    [1070, "m", "idZ ´Lw, iÖLþÿ K´w„"],
    [1071, "m", "BxZpwo„"],
    [1072, "m", "Gxgc KyU„"],
    [1073, "m", "Awxhmwe xbtw, Mwxl ew´w„"],
    [1074, "m", "AwV, 8„"],
    [1075, "m", "XwKd„"],
    [1076, "m", "Ax´, m¢Ø„"],
    [1077, "m", "iwp?„"],
    [1078, "majap", "RlKytw„"],
    [1079, "m", "fUwKwxd„"],
    [1080, "m", "LpUw„"],
    [1081, "majèp", "?K"],
    [1082, "m", "iÖVw, ÌmwUwB ´Lw„.K"],
    [1083, "m", "hwl Èhw\\ oóeÒ„"],
    [1084, "m", "GËdB„"],
    [1085, "m", "ewMl, iÔLê„"],
    [1086, "m", "ÌPËlKw„"],
    [1087, "m", "gëbgþæ K´w„"],
    [1088, "m", "iwxU KwV f×lw„"],
    [1089, "m", "Ìgwgw„"],
    [1090, "matu", "xKdw´, Kw´Y, Duo„"],
    [1091, "m", "Ìjw´w xbtw, g¬w„"],
    [1092, "m", "LÖëbw ÌLw\\w„"],
    [1093, "m", "D£´„"],
    [1094, "m", "xPKZw„"],
    [1095, "m", "Kw^p„"],
    [1096, "mahtut tsì", "Kwp´ bw\\wt„"],
    [1097, "mahtó", "aÖ ÌeËlw\\w„"],
    [1098, "m", "bÖ´Ðl ÌPw\\w, hwxg ÌPw\\w„"],
    [1099, "m", "Âdw, mÞ\\Y K´w„"],
    [1100, "m", "opwt K´w„"],
    [1101, "m", "xZI\\w„"],
    [1102, "m", "xZZw, Aw©ê„"],
    [1103, "m", "Ìg´, ?K"],
    [1104, "m", "eÞcwd„"],
    [1105, "m", "ÌbLÖ\\w, eÞbmêd K´w„"],
    [1106, "m", "Ìjw\\w xdmw„"],
    [1107, "m", "iwxlP K´w, ÌPxe c´w„"],
    [1108, "m", "eÖ\\w, Dbt„"],
    [1109, "m", "AxZxa, AwMìçK„"],
    [1110, "m", "ÌMw¬ Ìlw\\w„"],
    [1111, "maning", "xgMZ gQ´„"],
    [1112, "m", "Ìjw\\w Kwxl„"],
    [1113, "m", "p^pw„"],
    [1114, "m", "Aegwb K´w„"],
    [1115, "m", "eÖ´Øn xlŠ„"],
    [1116, "manyen", "xePl„"],
    [1117, "m", "´ØKw„"],
    [1118, "m", "bwi, b´„"],
    [1119, "m", "eËKw\\w„"],
    [1120, "m", "dPw, dwP, dÙZø„"],
    [1121, "manôn", "Ìlwh K´w„"],
    [1122, "manót", "DËVw\\w, bwxO xdtw„"],
    [1123, "m", "xpi, g´f„"],
    [1124, "m", "PÖgwB ÌLw\\w„"],
    [1125, "m", "PwK´„"],
    [1126, "m", "KŸ, LÖlwly eq„"],
    [1127, "m", "iËd iËd, ÌMweËd„"],
    [1128, "mayoi", "ÌRwOw K´w„"],
    [1129, "m", "DËVw\\w, ZÖlw„"],
    [1130, "m", "Kwi, KZêgø, hÔl ¢ØxU„"],
    [1131, "m", "idZ e´w„"],
    [1132, "m", "RÖxi ÌPw\\w„"],
    [1133, "m", "PÖP´wB xdtw„"],
    [1134, "m", "jiR„"],
    [1135, "m", "ÂOw„"],
    [1136, "m", "AdÖZwe K´w„"],
    [1137, "malaga", "icÔx´ Awi„"],
    [1138, "m", "KVwl„"],
    [1139, "malan", "xPcw K´w„"],
    [1140, "m", "ewp´w„"],
    [1141, "m", "ovLøw 4„"],
    [1142, "m", "PPw„"],
    [1143, "m", "pwxg„"],
    [1144, "m", "cewZ„"],
    [1145, "m", "PKÖ„"],
    [1146, "m", "dwi„"],
    [1147, "m", "id, xP£„"],
    [1148, "m", "PKÖixY„"],
    [1149, "m", "?K"],
    [1150, "myitai", "GUw PK× KYw„"],
    [1151, "m", "iŠlxZ„"],
    [1152, "m", "A¬„"],
    [1153, "myin", "eKw„"],
    [1154, "m", "A¬„"],
    [1155, "m", "PK× KYw„"],
    [1156, "myìprui", "PK×ewdy, AmÞØ„"],
    [1157, "myihprap", "xgRÖly„"],
    [1158, "myì man", "dwK KwY„"],
    [1159, "m", "PK× Ìdwi„"],
    [1160, "mùk", "xeVw,´ØxU„"],
    [1161, "mùng", "Ìmn, ´wRø„"],
    [1162, "mùng", "eÞcwd iìèy„"],
    [1163, "mungkán", "RMu, ovow´, xgmò„"],
    [1164, "m", "Ìbm„"],
    [1165, "m", "´wRø„"],
    [1166, "munghpyí", "ÈMê, o´M„"],
    [1167, "mut", "eL´w„"],
    [1168, "mun", "Ìdwi, ewLy„"],
    [1169, "mup", "†xs K´w„"],
    [1170, "mû", "Ìow\\wb, ÈwxbÄ„"],
    [1171, "mú", "ÌbLw„"],
    [1172, "m", "ÌhwU„"],
    [1173, "mé", "Ìlw\\w!"],
    [1174, "myek", "g´my„"],
    [1175, "myeng", "dÖxi Ìjw\\w„"],
    [1176, "myet", "MQKw„"],
    [1177, "Myen", "giêw´ ÌlwK gw ÌZI^ËlwK´ hwnw„"],
    [1178, "mô", "Dewt, ÌK#ml„"],
    [1179, "mok", "l!"],
    [1180, "mông", "D´w, xgtew„"],
    [1181, "mót", "N^w ÌLw\\w„"],
    [1182, "mon", "Ahøwo Ìpw\\w„"],
    [1183, "mop", "VMw, KeU K´w„"],
    [1184, "mai", "opR, hwl, Ìgiw´´ e´w hwl Ìew\\w„"],
    [1185, "maihpan", "?ÌPË´Ky„"],
    [1186, "mailung", "KwV„"],
    [1187, "mau", "hgw, AwPx´Z Ìpw\\w„"],
    [1188, "mauhpyí", "xhLw´y„"],
    [1189, "moi", "AwMZ, AZyZ KwlZ„"],
    [1190, "ya", "Ahøwo Ìpw\\w„"],
    [1191, "yamà", "ji ´Rw„"],
    [1192, "yà", "GxZtw, GB iÖÉZêZ„"],
    [1193, "yâ", "xbtw, AeêY K´w„"],
    [1194, "yá", "ÌoBtw!"],
    [1195, "yàk", "KÄ,KxVd, KxVdZw„"],
    [1196, "yagù", "iw´ hwZ„"],
    [1197, "yang", "jxb„"],
    [1198, "yàt", "xeUw, ePw„"],
    [1199, "yân", "mwx´, gwKø„"],
    [1200, "yàp", "pwxg KUw„"],
    [1201, "yam", "PwK´ LËUw\\w„"],
    [1202, "yàm", "xdt´„"],
    [1203, "yì/wì", "gwi ÌLxZ´ eaw´„"],
    [1204, "yìngam", "A^wP„"],
    [1205, "yin/win", "NÖ´w, ex´¸iY K´w„"],
    [1206, "yìnam", "gnêw„"],
    [1207, "yìhku", "ÌL´„"],
    [1208, "yit/wit", "ewvLw iw´w, xgPw„"],
    [1209, "yu", "ÌPw\\w, bmêd K´w„"],
    [1210, "yuhkóng", "Mlw„"],
    [1211, "yù", "diw, dwxi Apw„"],
    [1212, "yùk", "dyP, ewL¡„"],
    [1213, "yung", "ex´cwd K´w„"],
    [1214, "yùn", "xPvËf# ex´twl´ AÄi Kdøw„"],
    [1215, "yû", "GëbÖ´, xdMxd„"],
    [1216, "yút", "xPvËf# ex´twl´ AUwBZÐK KxdÅ eÖ¢ gw eÖ¢y„"],
    [1217, "yùp", "Â\\w, mtd K´w„"],
    [1218, "yupngà", "ÌUwedytw„"],
    [1219, "yuppui", "ht lMw oËewd ÌbLw„"],
    [1220, "yupmàng", "oËewd„"],
    [1221, "yum", "xgmòwo K´w„"],
    [1222, "yùm", "pwDlw, ZliÖ´ K´w„"],
    [1223, "yen/wen", "Aw^Z´w, AwZx´ xbtw„"],
    [1224, "yong", "†xP Ìjw\\w„"],
    [1225, "yò", "LÖD\\w„"],
    [1226, "yòng", "ogµê, ÌMwËUB, oKËlw„"],
    [1227, "yông", "Ñg Ìjw\\w„"],
    [1228, "yòm", "Ki, oþæw„"],
    [1229, "yó", "p’g? ÌbB„"],
    [1230, "yôn", "ÌgRw´ K´w„"],
    [1231, "ra", "oiwd„"],
    [1232, "rà", "hwl Ìew\\w, Rwxe ´Lw„"],
    [1233, "rá", "lMw,Aw\\møK Ìpw\\w„"],
    [1234, "ràng", "Kwi Dx¥edw Ìpw\\w„"],
    [1235, "râng", "DxV aKw„"],
    [1236, "râ-tâ", "gpwM„"],
    [1237, "ràt", "KUw, KwUd ÌLw\\w„"],
    [1238, "ràn", "?K"],
    [1239, "ràp", "ew´ Ìpw\\w, ÌelwB xbtw„"],
    [1240, "ràm", "jËVÄ, HKøg¦ K´w„"],
    [1241, "ri", "ÌgZ„"],
    [1242, "rì", "K^ew„"],
    [1243, "rî", "Wwl hx´ fl lMw„"],
    [1244, "rí", "oÖZw„"],
    [1245, "rít", "eËKw\\w„"],
    [1246, "rìn", "†xs K´w, ÌPew„"],
    [1247, "rìp", "ÌelwB xbtw, bxl iw´w„"],
    [1248, "rìm", "c´w, AwZK K´w„"],
    [1249, "rùng", "AwbwlZ„"],
    [1250, "rûng", "xmv„"],
    [1251, "rút", "odw„"],
    [1252, "rùn", "LÖlw„"],
    [1253, "rùm", "cµvo, eZd Ìpw\\w„"],
    [1254, "rûm", "xilw RÖlw, GËKB„"],
    [1255, "rèng", "lwMxZtwl„"],
    [1256, "rèt", "Kwxs xdtw„"],
    [1257, "rèm", "´Lw, P´w, Ìewpewl K´w„"],
    [1258, "ré", "p’t„"],
    [1259, "rét", "K´ËZË´ KUw„"],
    [1260, "rén", "byNl„"],
    [1261, "rò", "LÖlw, iÖKlw„"],
    [1262, "ròk", "Kaw ewZw„"],
    [1263, "ròng", "aKw, xdxpZ„"],
    [1264, "ròng rai", "gt gþç„"],
    [1265, "róng", "xPT´w„"],
    [1266, "rót", "DVw, DÒZ Ìpw\\w„"],
    [1267, "rai", "gþç, p’t„"],
    [1268, "rai jang", "jxb„"],
    [1269, "rai yang", "jxb„"],
    [1270, "rau", "Ìo\\d K´w, lMZ„"],
    [1271, "râu", "AwRx´ aKw„"],
    [1272, "roi", "Awixd K´w,xPvËf# ex´twl´ ZÙZyt Kdøw„"],
    [1273, "la", "eÖ´Øn„"],
    [1274, "lakchyóp", "AwOÖxV„"],
    [1275, "lakang", "pwZ hx´ Ìixl gpw„"],
    [1276, "lakan", "KwYf×ly„"],
    [1277, "la-kàn", "dMí, dOVw„"],
    [1278, "laká", "p^Ëpw\\w„"],
    [1279, "lakâng", "RLlw„"],
    [1280, "lakáp", "ÌPËedw„"],
    [1281, "lakòng", "xPKw´y„"],
    [1282, "lakyì", "K"],
    [1283, "lakying", "Xwl, mwLw„"],
    [1284, "lakyin", "ÌlËpi„"],
    [1285, "lakung", "PwËiwP„"],
    [1286, "lahkat", "lwV iw´w„"],
    [1287, "lahkan", "eli K´w„"],
    [1288, "lahkàp", "K"],
    [1289, "lahkàm", "gwÉ,?"],
    [1290, "lahká", "Ìow^, Kxstw„"],
    [1291, "lahkí", "ÌK´w AwOÖxl„"],
    [1292, "lahkum", "PKy, xesw„"],
    [1293, "lahkong", "bÖB (2)„"],
    [1294, "lahkòn", "Lw´Ø„"],
    [1295, "lahkón", "Riw K´w, ÌMwËUw\\w„"],
    [1296, "lagat", "Ìb#´ iw´w„"],
    [1297, "lagát", "Ìi# iwLy„"],
    [1298, "lagan", "lÖKwB ´Lw, †® ´Lw„"],
    [1299, "l", "Rwe iw´w„"],
    [1300, "lagyim", "lÖËKw\\w, ÌMweËd ´Lw„"],
    [1301, "lagû", "ÌPw´ K´w„"],
    [1302, "lagùt", "ÌPw´„"],
    [1303, "lagòn", "bMw, GËlÉ\\w„"],
    [1304, "lang", "gø\\pw´ K´w, c´w„"],
    [1305, "langdáng", "M†Y„"],
    [1306, "làng", "xPcw K´w gw Ìpw\\w„"],
    [1307, "lâng", "MQ KUw„"],
    [1308, "langà", "Kl eÖxl„"],
    [1309, "langan", "?K"],
    [1310, "langû", "Kl„"],
    [1311, "langai", "GK (1)„"],
    [1312, "latsâ", "m, (100)"],
    [1313, "latsáng", "hx´´ AwOÖly„"],
    [1314, "latsâng", "?K"],
    [1315, "lajang", "K´w, ÑZtw´ K´w„"],
    [1316, "lajà", "KÄbwtK, KxVd„"],
    [1317, "lajâ", "Gxgc MQ„"],
    [1318, "latà", "pwZ, gwÉ, gwxP Ìlw\\w„"],
    [1319, "latung", "ÌewK„"],
    [1320, "lahtà", "Ie´, D£´ xbm„"],
    [1321, "lahtin", "?g"],
    [1322, "lahtum", "†Pw iw´w„"],
    [1323, "lanû", "gÖsw AwOÖxl„"],
    [1324, "lapai", "gwI„"],
    [1325, "lapran", "iwRZ, xhZ´Z„"],
    [1326, "lahpà", "Kwëb„"],
    [1327, "lahpán", "ZËlw\\w„"],
    [1328, "lahpyî", "ÌlËO´w„"],
    [1329, "lahput", "AwVÖ„"],
    [1330, "laban", "Lwly, Agøþæ„"],
    [1331, "labù", "ÌcwxU, PÖx´tw„"],
    [1332, "labû", "xgp„"],
    [1333, "labau", "gÖ´™y„"],
    [1334, "labyé", "ÌlËO´w, ÌRwZw„"],
    [1335, "lamà", "jxb„"],
    [1336, "laman", "oit„"],
    [1337, "lamyik", "xdQwdw, Awbmê„"],
    [1338, "lamyin", "dL„"],
    [1339, "lawan", "ÌowdKwËl„"],
    [1340, "lawù", "Zl, bxqY„"],
    [1341, "lasà", "xm´„"],
    [1342, "lasà rú", "xm´ e¦xZ„"],
    [1343, "là", "xPvËf# ex´twl´ ZÙZyt eÖ¢, g¬ K´w„"],
    [1344, "làk", "LÖxU„"],
    [1345, "lát", "AËeqw K´w, xPvËf# ex´twl´ eÞai oìæwd„"],
    [1346, "lì", "xe¬w„"],
    [1347, "lî", "hwx´, dwI„"],
    [1348, "lik", "xKZwe, MÞìÿ„"],
    [1349, "ling", "ÂoÞnw K´w, h´Y ÌewnY K´w„"],
    [1350, "lit", "bwxt£ò, KZêgø„"],
    [1351, "lim", "WÖgw„"],
    [1352, "lù", "ey ÌLw\\w, xPvËf# ex´twl´ x§Zyt Kdøw„"],
    [1353, "lû", "bwd K´w, DPMêw K´w„"],
    [1354, "lú", "Ìew\\w, eÞw® Ìpw\\w„"],
    [1355, "lung", "DVw, Dx£Yê Ìpw\\w„"],
    [1356, "lut", "LwlZ e´w„"],
    [1357, "ludì", "cewZ ÌLw\\w xeew„"],
    [1358, "lup", "eÖZw, mômwd„"],
    [1359, "lè", "gwxp´Ðl Ilw„"],
    [1360, "leng", "´a, Mwry„"],
    [1361, "lèng", "gwM´w„"],
    [1362, "let", "ÌKw\\w´xePZ, ÑKÑl„"],
    [1363, "lèn", "oit dÄ K´w, eli K´w„"],
    [1364, "lông", "lv †xU„"],
    [1365, "lóka", "RMu, ovow´„"],
    [1366, "lot", "gwxP Ìjw\\w, iÖ£Ø Ìpw\\w„"],
    [1367, "lòn", "´v Ìciwly K´w„"],
    [1368, "lóhpa", "Ìlwh, Ìlwh K´w„"],
    [1369, "lau", "VMw, Ql KeU K´w„"],
    [1370, "làu", "lÖxUtwB xbtw„"],
    [1371, "loi", "DejÖ£Ø„"],
    [1372, "wa", "xdËR„"],
    [1373, "wà", "h´w, Mwp´y„"],
    [1374, "wà ndú", "mÔK´, gd´yt Mwp´y„"],
    [1375, "wà ndú nâ", "ÌMwg´Ø\\w„"],
    [1376, "wâ", "bw^Z„"],
    [1377, "wá", "xeZÙ, Apw gw Ìjw\\w„"],
    [1378, "wàk", "ÑgVw iw´w, ewdy xo^Pw„"],
    [1379, "wakang", "dwI„"],
    [1380, "wahkà", "bw^Z hMw„"],
    [1381, "wahkang", "Ìow^ iwRZ„"],
    [1382, "wahkyi", "bw^Z´ ?"],
    [1383, "wahkum si", "ÌKwËiw´w„"],
    [1384, "wahkeng", "ÌRD´w LÖxU„"],
    [1385, "wàng", "Aw†xP c´w„"],
    [1386, "wâng", "AwPx´Z Ìpw\\w„"],
    [1387, "wàt", "ÌRwK„"],
    [1388, "wàn", "RÖB, xdRÖly„"],
    [1389, "wanhkut", "Ìcw^\\w„"],
    [1390, "wanhkret", "PlwB„"],
    [1391, "wan", "GOw´„"],
    [1392, "wanjî", "?K"],
    [1393, "wanbùng", "ÌfwifwB„"],
    [1394, "wanmang", "RÖmwl„"],
    [1395, "wanlî", "xmLw„"],
    [1396, "wáp", "ÌoË´Ow, Lwly„"],
    [1397, "wâm", "NÖx´ f×´w„"],
    [1398, "warâ", "Gxgc gwp„"],
    [1399, "warong", "bw^ZÖly„"],
    [1400, "wì/yì", "gwi ÌLxZ´ eaw´„"],
    [1401, "wìwa", "UxO N´„"],
    [1402, "wí", "iwBKy„"],
    [1403, "wù", "Axhmwe xbtw„"],
    [1404, "wuk", "RÖB lMw„"],
    [1405, "wut", "ewe, CUw, ÌRV iwp, RÖB RËlw\\w„"],
    [1406, "wudang", "?"],
    [1407, "we/ye", "Sw´Ø iw´w„"],
    [1408, "wen/yen", "AwZ´, ZøwM K´w„"],
    [1409, "wem", "Këbw„"],
    [1410, "wo", "Mwxl ew´w„"],
    [1411, "wò", "xg¬w fÖËUw\\w„"],
    [1412, "wó", "Pxbê, ewdy lMw„"],
    [1413, "wòt", "iŠl ÌPw\\w„"],
    [1414, "wôn", "hÔ´„"],
    [1415, "wón", "K"],
    [1416, "woi", "gwd´, gwëb´„"],
    [1417, "wau", "hÖKw„"],
    [1418, "wòi", "Ìmn Ìpw\\w, Aìæ e´w„"],
    [1419, "sa", "Ìjw\\w„"],
    [1420, "sanghpó", "dwI, RwpwR„"],
    [1421, "sàn", "Ìowcw, eÞmí K´w„"],
    [1422, "sàn poi", "e´yqw„"],
    [1423, "sanát", "gëbÖK„"],
    [1424, "sanit", "owZ (7)„"],
    [1425, "samyit", "ÌgRy„"],
    [1426, "slang", "ipwmt„"],
    [1427, "salang-jàn", "ipwmtw„"],
    [1428, "salau", "l´w„"],
    [1429, "salau-si", "LÖU×´w mwK„"],
    [1430, "sà", "xR´Yy Ìlw\\w„"],
    [1431, "sí", "mwK, ewPly„"],
    [1432, "sí nmì", "ewPly„"],
    [1433, "símai", "mwK ewPly„"],
    [1434, "sî", "Bp (10), iÙZ×ø Ìpw\\w„"],
    [1435, "sít", "Ì´Lw Udw„"],
    [1436, "sin", "myl„"],
    [1437, "sinam", "Awbw„"],
    [1438, "sinhkû", "xpv„"],
    [1439, "sin mangâ", "eémyl„"],
    [1440, "sin-langà", "Ms„"],
    [1441, "sut", "cd„"],
    [1442, "sutgan", "oóex£„"],
    [1443, "sutokóng", "†Ygwd„"],
    [1444, "sutóng", "eÞwaêdw K´w„"],
    [1445, "sun", "gwx´, Kóed Ìpw\\w„"],
    [1446, "sù", "Ìi«K, Ìgv„"],
    [1447, "sùt", "AwV×\\w„"],
    [1448, "sú", "cdy, PpKy„"],
    [1449, "sùp", "Xlw„"],
    [1450, "supséng", "Zwl„"],
    [1451, "sùm", "Ìp´Ø\\w, dÖKPwd Ìpw\\w„"],
    [1452, "sûm", "lÖYytw, e’l„"],
    [1453, "sumgón", "iwQ i´w Rwl„"],
    [1454, "sumdoi", "lwLÖxU„"],
    [1455, "s", "Ìow´w„"],
    [1456, "sumpai", "pw^IfwI„"],
    [1457, "sumpát", "E"],
    [1458, "sumpyî", "gwbø jìè„"],
    [1459, "sumprang", "Lx´Kw„"],
    [1460, "sumhpai", "pwZy g¬w ´xQ„"],
    [1461, "summun", "cÔly, AYÖ, KxYKw„"],
    [1462, "sumrî", "´xQ„"],
    [1463, "sé", "eÞKwm K´w, DâPw´Y K´w„"],
    [1464, "sékap", "bxqYw„"],
    [1465, "seng", "b´Kw´„"],
    [1466, "seng", "Aìæ Kx´ ÌeËlw\\w„"],
    [1467, "seng", "ÌbwKwd„"],
    [1468, "sèng", "ixY iÖK×Zw„"],
    [1469, "sot", "xdxQdw, bË´„"],
    [1470, "sai", "ÌZR, idZ e´w„"],
    [1471, "saihkat", "eËKw\\w ´xQ„"],
    [1472, "saileng", "Pwl gw^DËZ i’p ÌLbw ÌgZ´ lwxVWwl„"],
    [1473, "sau", "Pxgê, ÌZl„"],
    [1474, "shakan", "LÖlw VwB„"],
    [1475, "shakà", "LÖlw„"],
    [1476, "shak", "gl xbtw„"],
    [1477, "shakyip", "ht LÖD\\w„"],
    [1478, "shakut", "Duowp K´w„"],
    [1479, "shakòng", "f×Uwxd iw´w„"],
    [1480, "shakòn", "eÞmvow K´w„"],
    [1481, "shakau", "xetwR„lPÖd„"],
    [1482, "shagan", "Z´w„"],
    [1483, "shagrit", "Ki K´w, Kiw„"],
    [1484, "shang", "eÞËgm K´w„"],
    [1485, "shangang", "KUKxUtw K´w„"],
    [1486, "shangan", "?iwp„"],
    [1487, "shachyut", "ZZwÐZtw K´w„"],
    [1488, "shachyen", "ex´Pt xbtw„"],
    [1489, "shajà", "ÌRw´ xbtw gw K´w„"],
    [1490, "shajan", "gwKy„"],
    [1491, "shat", "hwZ, Lwbø„"],
    [1492, "shatâ", "Pë©, iwp„"],
    [1493, "shatan", "K?"],
    [1494, "shaten", "ÌgM gÙx¦ K´w„"],
    [1495, "shadung", "xPvËf# ÌlwK oKl´ RwZyt xdQwd„"],
    [1496, "shadû", "´¬w„"],
    [1497, "shadú", "Ìew\\wB xbtw„"],
    [1498, "shan", "bÖRd, iwvo„"],
    [1499, "shaning", "gQ´„"],
    [1500, "shanhténg", "xop^Z, ÌZËLZoKl„"],
    [1501, "shap", "DxlI\\w, gw´w„"],
    [1502, "sháp", "cw´Z Ìlw\\w, hw´wZ Ìlw\\w„"],
    [1503, "shapá", "gÉZ„"],
    [1504, "shapan", "WwO´ byNl K´w„"],
    [1505, "shaprang", "GUw´ xeQZ GUw DxlI\\w„"],
    [1506, "shaprat", "Ìewp ewl K´w„"],
    [1507, "shabyî", "Mwl„"],
    [1508, "shabòng", "ÌglÖd„"],
    [1509, "shá", "ÌLw\\w, ÌhwRd K´w„"],
    [1510, "shá", "LK×\\w„"],
    [1511, "sharam", "Eb xglwt„"],
    [1512, "sharà", "xpvow K´w„"],
    [1513, "sharâ", "oiwd K´w„"],
    [1514, "s", "VwB, þÿwd„"],
    [1515, "sharun", "Ìixl xbtw„"],
    [1516, "shari", "hwMø„"],
    [1517, "sharè", "K"],
    [1518, "sharé", "owpoy„"],
    [1519, "shareng", "odôwd K´w„"],
    [1520, "sharò", "Rìç„?"],
    [1521, "sharông", "gwN„"],
    [1522, "sharót", "DËVw\\w, RËMw\\w„"],
    [1523, "sharin", "xmKw gw xmËKw\\w„"],
    [1524, "shalâ", "Qxg, eÖZlw„"],
    [1525, "shalàt", "Nwi„"],
    [1526, "shalá", "RÖKw„"],
    [1527, "shalá-tâ", "-iwp„"],
    [1528, "shalik", "xPMwË´U„"],
    [1529, "shalip", "?K"],
    [1530, "shali-wunli", "oóex£, D£´wxcKw´„"],
    [1531, "shalút", "?K"],
    [1532, "shalun", "DVwB xbtw„"],
    [1533, "shalum", "KxlRw„"],
    [1534, "shawa", "´wBR„"],
    [1535, "shi", "ÌZI^, xo„"],
    [1536, "shing", "ÌoB xdxQdw, ewKN´„"],
    [1537, "shinggan", "gwxp´, xgËbm„"],
    [1538, "shinggyim", "iwd\\„"],
    [1539, "shinggran", "id:KxùeZ, KwùexdK„"],
    [1540, "shingtai", "AKl,ÌK\\l iw¢„"],
    [1541, "shingdim", "xeQZ„"],
    [1542, "shingdù", "xexV„"],
    [1543, "shingnip", "Qw^„"],
    [1544, "shinglet", "xRhw„"],
    [1545, "shinglen", "ÌdDl„"],
    [1546, "shû", "ÌKw\\w, eÞKwm K´w„"],
    [1547, "shòng", "†´Ø£òeÔYê„"],
    [1548, "sh", "AwMfwl, AwM´„"],
    [1549, "shóp", "oÖëb´, cÖdytw„"],
    [1550, "hàp", "bwxtZò„"],
    [1551, "hàngshi", "xovp„"],
    [1552, "háng", "ÑZtw´ K´w, owxP ´Lw„"],
    [1553, "hán", "Gxgc WwV ´v„"],
    [1554, "hying", "pwRw´„"],
    [1555, "hung", "xgLøwZ„"],
    [1556, "hup", "iÖUwiÖxU„"],
    [1557, "heng", "eÞgl„"],
    [1558, "hém", "ÑZtw´ K´w„"],
    [1559, "hó", "Ìbmdw K´w, eÞgPdw K´w„"],
    [1560, "hóm", "oÖM¬, oÖM¬y„"],
    [1561, "", "ÌK\\l GUw È´ gYê Aw´Ø GUw gø™d gYêË´ MVYÌpw\\w m²„"],
    [1562, "kà", "UÖi„"],
    [1563, "hkà", "ewdy, dby„"],
    [1564, "gà", "fUw„"],
    [1565, "ngà", "iwQ„"],
    [1566, "chyà", "lwxM c´w„"],
    [1567, "tsà", "oÖ´w„"],
    [1568, "jà", "ewdy ÌZwlw, KxVd, Uwd„"],
    [1569, "ñà", "K"],
    [1570, "tà", "xdxQdw, ÌPËlxK ÌLw\\w„"],
    [1571, "htà", "ZÖxl Ìlw\\w, gÖUxl Ìlw\\w„"],
    [1572, "dà", "KwËew´ Ìgw\\w„"],
    [1573, "nà", "dwewt, K´w DxPZ dp’t„"],
    [1574, "pà", "diw, gpw„"],
    [1575, "hpà", "iw´ hwZ„"],
    [1576, "bà", "ÌgwËKwPwZ Ìlw\\w, Mhê\\Zy Ìpw\\w„"],
    [1577, "mà", "Ìmn K´w, Aìæ K´w„"],
    [1578, "yà", "GxZtw„"],
    [1579, "rà", "hwl Ìew\\w, Ie´Z ÌZwlw„"],
    [1580, "là", "g¬ K´w, xPvËf# ex´twl´ ZÙZyt eÖ¢„"],
    [1581, "wà", "ex´Ëmwc K´w, Mwp´y„"],
    [1582, "sà", "xR´Yy Ìlw\\w, Dmw Ìlw\\w„"],
    [1583, "kâ", "xlLw, dPw„"],
    [1584, "hkâ", "Kwl„"],
    [1585, "gâ", "Ìgew´ K´w„"],
    [1586, "ngâ", "ÌKw\\w, ip„"],
    [1587, "chyâ", "odw, AKw„"],
    [1588, "tsâ", "m (100)„"],
    [1589, "jâ", "K"],
    [1590, "tâ", "iwp„"],
    [1591, "dâ", "bmêd, xgmòwo,iZ„"],
    [1592, "nâ", "KwY„"],
    [1593, "pâ", "?K"],
    [1594, "hpâ", "xdxQdw, bË´„"],
    [1595, "b", "ZlZytw Ìpw\\w„"],
    [1596, "mâ", "xdQwZ f×´w„"],
    [1597, "yâ", "xbtw„"],
    [1598, "râ", "oiwd„"],
    [1599, "lâ", "eÖ´Øn, exZ„"],
    [1600, "wâ", "bw^Z„"],
    [1601, "sâ", "Ìjw\\w, MiY K´w„"],
    [1602, "ká", "ÌRøÅ„"],
    [1603, "hká", "lMw, cw´, xPvËf# ex´twl´ nÅ Kdøw„"],
    [1604, "gá", "gÉ, AovLø„"],
    [1605, "ngá", "gwo K´w, aKw„"],
    [1606, "tsá", "ÌiwiwËtK„"],
    [1607, "já", "gøt K´w„"],
    [1608, "htá", "Mwxlew´w, eMlw Ìpw\\w„"],
    [1609, "dá", "ÌoBtw!"],
    [1610, "ná", "ÌbB!, eaw´„"],
    [1611, "hpá", "ewZl„"],
    [1612, "bá", "gwBÌbD„"],
    [1613, "K", "KË´ Aìæ Ìpw\\w m²„"],
    [1614, "kàk", "K"],
    [1615, "hkàk", "xePw„"],
    [1616, "hkràk", "G?"],
    [1617, "gàk/gràk", "xVK, DejÖ£ß„"],
    [1618, "ngàk", "hwx´„"],
    [1619, "chyàk", "K"],
    [1620, "tsàk", "K"],
    [1621, "jàk", "ÌixPd, Bx™d„"],
    [1622, "ñàk", "K"],
    [1623, "tàk", "K"],
    [1624, "htàk", "xPxM Ìjw\\w„"],
    [1625, "dàk", "diw„"],
    [1626, "nàk", "hwx´„"],
    [1627, "pàk", "Wwlw„"],
    [1628, "hpàk", "KUw, Ìawew„"],
    [1629, "bàk", "iÖLËZ ÑK xbtw„"],
    [1630, "màk", "M¬„"],
    [1631, "yàk", "KÄ, KxVd„"],
    [1632, "ràk", "K"],
    [1633, "làk", "LÖxU„"],
    [1634, "sàk", "gto„"],
    [1635, "Ng", "OË´ Aìæ Ìpw\\w m²„"],
    [1636, "àng", "lMw„"],
    [1637, "âng", "ÌU#„"],
    [1638, "áng", "ÌUUÖ„"],
    [1639, "ìng", "WÖgw„"],
    [1640, "ung", "hx´ aKw„"],
    [1641, "òng", "oìçÄ Ìpw\\w„"],
    [1642, "kàng", "RÖBZ ZeZ xbtw„"],
    [1643, "hkàng", "g¬w„"],
    [1644, "gàng", "Udw„"],
    [1645, "ngàng", "iRgÖZ„"],
    [1646, "chyàng", "xPìæw K´w, K’lw„"],
    [1647, "tsàng", "ÌgM„"],
    [1648, "jàng", "ÌowdKwËl„"],
    [1649, "ñàng", "aKw„"],
    [1650, "t", "DPMêw K´w, xPvËf# ex´twl´ eéi eÖ¢„"],
    [1651, "htàng", "NÖ´w, D£´ xbtw„"],
    [1652, "dàng", "lwxM c´w„"],
    [1653, "nàng", "ZÖxi, AweÖxd„"],
    [1654, "pàng", "K"],
    [1655, "hpàng", "Aw´º K´w„"],
    [1656, "bàng", "hË´w\\w, ÌhwU xbtw„"],
    [1657, "màng", "iÙZ Ìbp, i´w m„"],
    [1658, "yàng", "jxb„"],
    [1659, "ràng", "Kwi Dx¥ed Ìpw\\w„"],
    [1660, "wàng", "AwËMwPw„"],
    [1661, "shàng", "eÞËgm K´w„"],
    [1662, "kâng", "iwR, Ìo^w iwR„"],
    [1663, "hkâng", "ÌLwR„"],
    [1664, "gâng", "Riw K´w, Awt£ K´w„"],
    [1665, "ngâng", "K"],
    [1666, "chyâng", "pwlKw, ewZl„"],
    [1667, "tsâng", "Kq, ÌmÞYy„"],
    [1668, "jâng", "owxP ´Lw„"],
    [1669, "ñâng", "K"],
    [1670, "tâng", "gwi„"],
    [1671, "htâng", "K"],
    [1672, "dâng", "K"],
    [1673, "nâng", "iZlytw„"],
    [1674, "pâng/prang", "gwx´„"],
    [1675, "hpâng", "K"],
    [1676, "bâng", "K"],
    [1677, "mâng", "xgiÖs„"],
    [1678, "yâng", "Ì´Lw, mwx´„"],
    [1679, "râng", "Ie´Z DxV aKw„"],
    [1680, "lâng", "KUw„"],
    [1681, "wâng", "PiK ÌLw\\w„"],
    [1682, "shâng", "K"],
    [1683, "T", "Z/UË´ Aìæ Ìpw\\w m²„"],
    [1684, "kàt", "gRw´„"],
    [1685, "hkàt", "Ie´´ e´w xM´w„"],
    [1686, "gàt", "Ìb#´ iw´w„"],
    [1687, "ngàt", "hwxO Ìjw\\w„"],
    [1688, "chyàt", "KUKxUtw„"],
    [1689, "tsàt", "K"],
    [1690, "jàt", "UÖK×´w K´w, jwxP Ìlw\\w„"],
    [1691, "tàt", "Gx´ xbtw„"],
    [1692, "htàt", "WwV„"],
    [1693, "dàt", "Xwlw, iÖ£ß K´w„"],
    [1694, "nàt", "Rlw, ÌbD, hÔZ„"],
    [1695, "pàt", "G¬ K´w, RwvfwB„"],
    [1696, "hpàt", "iw´w, esw„"],
    [1697, "bàt", "iw´w, gxpÆw´ K´w, o®wp„"],
    [1698, "màt", "K"],
    [1699, "yàt", "ePw„"],
    [1700, "ràt", "KUw„"],
    [1701, "làt", "ÌKxPË´ KUw„"],
    [1702, "wàt", "ÌRwK„"],
    [1703, "sàt", "iwx´ ÌeËlw\\w, dÄ K´w„"],
    [1704, "shàt", "AÒ, hwZ„"],
    [1705, "kát", "gÉZ Uwd„"],
    [1706, "hkát", "bwp Ìpw\\w„"],
    [1707, "gát", "ew´w (KxVtw)„"],
    [1708, "ngát", "K"],
    [1709, "chyát", "K"],
    [1710, "tsát", "Rxetw„"],
    [1711, "ját", "Rdô, dwUK„"],
    [1712, "tát", "?K"],
    [1713, "htát", "lwMxZtwl„"],
    [1714, "dát", "K"],
    [1715, "nát", "AwDRw„"],
    [1716, "pát/prát", "gto, Kwl„"],
    [1717, "hpát", "K"],
    [1718, "bát", "K"],
    [1719, "mát", "Ìp´wB Ìjw\\w, Ìp´Ø\\w„"],
    [1720, "yát", "Ilxi aKw„"],
    [1721, "rát", "K"],
    [1722, "wát", "ex´Ëmwc xbtw„"],
    [1723, "sát", "Apw Ìjw\\w K´w„"],
    [1724, "N", "dË´ Aìæ Ìpw\\w m²„"],
    [1725, "kàn", "ÌeU„"],
    [1726, "hkàn", "Ìpew„"],
    [1727, "gàn", "U×edy ÌdwËjw\\w„"],
    [1728, "ngàn", "pwK xbtw, Mwxl ew´w„"],
    [1729, "chyàn", "K"],
    [1730, "tsàn", "gPw„"],
    [1731, "jàn", "Awixd lMw„"],
    [1732, "ñàn", "K"],
    [1733, "tàn", "hwxO Ìjw\\w„"],
    [1734, "htàn", "AËPZd Ìpw\\w„"],
    [1735, "dàn", "KUw, xV´wv K´w, ipw§ye„"],
    [1736, "nàn", "eÖd´ K´w„"],
    [1737, "pàn", "gwcw K´w„"],
    [1738, "hpàn", "RwxZ, gMê„"],
    [1739, "bàn", "gwM´w, gwcw K´w„"],
    [1740, "màn", "Lwly„"],
    [1741, "yàn", "K"],
    [1742, "ràn", "?K"],
    [1743, "wàn", "AxMí, RÖB„"],
    [1744, "sàn", "Ìowcw„"],
    [1745, "shàn", "iwvo, xop^Z bÖRd„"],
    [1746, "P", "eË´ Aìæ Ìpw\\w m²„"],
    [1747, "kàp", "lwxM c´w, lMw„"],
    [1748, "hkàp", "AwËMwPw„"],
    [1749, "hkràp", "Këbw„"],
    [1750, "gàp", "xdiêwY K´w„"],
    [1751, "ngàp", "g¬ Ìpw\\w (m²)„"],
    [1752, "chyap", "g"],
    [1753, "tsàp", "xVt Ìpw\\w, hwlÖK„"],
    [1754, "j", "Swl„"],
    [1755, "ñàp", "´qw g¬d K´w„"],
    [1756, "tàp", "Ìmn Ìpw\\w„"],
    [1757, "htàp", "ÌPwKw„"],
    [1758, "dàp", "QwB„"],
    [1759, "nàp", "eÖ\\w„"],
    [1760, "pàp", "g"],
    [1761, "hpàp", "g"],
    [1762, "bàp", "g"],
    [1763, "màp", "g"],
    [1764, "yàp", "pwxg ÌRw´w„"],
    [1765, "ràp", "ew´ Ìpw\\w, ÌelwB xbtw„"],
    [1766, "làp", "ewZ„"],
    [1767, "wàp", "g"],
    [1768, "sàp", "Lwxëb DxlI\\w„"],
    [1769, "shàp", "g"],
    [1770, "hàp", "bwxt£ò„"],
    [1771, "P", "eË´ Aìæ Ìpw\\w m²„"],
    [1772, "káp", "pwZZ ZÖxl xbtw„"],
    [1773, "hkáp", "g"],
    [1774, "gáp", "†xl iw´w„"],
    [1775, "ngáp", "g"],
    [1776, "chyáp", "g"],
    [1777, "tsáp", "Sw´w„"],
    [1778, "jáp", "g"],
    [1779, "ñáp", "g"],
    [1780, "táp", "gRw´„"],
    [1781, "htáp", "g"],
    [1782, "dáp", "IlwB e´w, Awxghêw\\ Ìpw\\w„"],
    [1783, "náp", "ZË´w\\wl„"],
    [1784, "páp", "ÌodwB xbtw„"],
    [1785, "hpáp", "g"],
    [1786, "báp", "g"],
    [1787, "máp", "g"],
    [1788, "láp", "g"],
    [1789, "wáp", "ÌpË´Ow„"],
    [1790, "sháp", "cw´Z Ìlw\\w„"],
    [1791, "M", "iË´ Aìæ Ìpw\\w m²„"],
    [1792, "am", "Ìew\\wly´ Lwbø„"],
    [1793, "kàm", "xgmòwoK´w,BâQw K´w„"],
    [1794, "hkàm", "fwëb eZw„"],
    [1795, "gàm", "hwM K´w, AwgåUd K´w„"],
    [1796, "ngàm", "gwKy aKw, gwKy gw RÖVw„"],
    [1797, "chyàm", "jËVÄ„"],
    [1798, "tsàm", "UxO Rwl„"],
    [1799, "jàm", "g"],
    [1800, "ñàm", "g"],
    [1801, "tàm", "xgP´w, AË¹nY K´w„"],
    [1802, "htàm", "mZK´w„"],
    [1803, "dàm", "Awpl gpl„"],
    [1804, "nàm", "pwxg, gd„"],
    [1805, "pàm", "g"],
    [1806, "hpàm", "LÉ„"],
    [1807, "bàm", "xZZw, Aw©ê„"],
    [1808, "màm", "g"],
    [1809, "yàm", "xdt´„"],
    [1810, "ràm", "gjËVÄ, oiwd„"],
    [1811, "làm", "iwMê, xgnt„"],
    [1812, "wàm", "g"],
    [1813, "", "È´ gYê(B)lMZgø™d gYê(O)Ë´ Aìæ Ìpw\\w m²„"],
    [1814, "ìng", "WÖgw (ewdyZ)„"],
    [1815, "kìng", "p"],
    [1816, "hkìng", "owRew´, ovÆÚxZ„"],
    [1817, "gìng", "iwdxoK mx£ß, DejÖ£ß„"],
    [1818, "ngìng", "p"],
    [1819, "chyìng", "ÌXwl„"],
    [1820, "tsìng", "xZD\\w„"],
    [1821, "ñìng", "p"],
    [1822, "tìng", "oiþæ , oiMÞ„"],
    [1823, "htìng", "p"],
    [1824, "dìng", "Nd„"],
    [1825, "nìng", "gnê, gQ´„"],
    [1826, "pìng", "Lx´KwZ xbtw„"],
    [1827, "hpìng/hpring", "hx£ê Ìpw\\w, oÖlh„"],
    [1828, "myìng", "dwi„"],
    [1829, "yìng", "p"],
    [1830, "rìng", "p"],
    [1831, "lìng", "ÂoÞnw K´w„"],
    [1832, "wìng", "p"],
    [1833, "hyìng", "pwRw´„"],
    [1834, "", "È´ gYê(D)lMZgø™d gYê(O)Ë´ Aìæ Ìpw\\w m²„"],
    [1835, "ùng", "g"],
    [1836, "kùng", "ÌPwKw, jZ´„"],
    [1837, "hkùng", "Awhw jÖ£ß, Ìewp´„"],
    [1838, "gùng", "Sw´w„"],
    [1839, "ngùng", "g"],
    [1840, "chyùng", "g"],
    [1841, "tsùng", "ewdyZ xZtwB Ìlw\\w„"],
    [1842, "jùng", "bÖgêl„"],
    [1843, "ñùng", "g"],
    [1844, "tùng", "ewdy gw´w„"],
    [1845, "htùng", "xdti, dyxZ, ´yxZ„"],
    [1846, "dùng", "gpw„"],
    [1847, "nùng", "g"],
    [1848, "pùng", "owcÖ Kaw, Dedøwo„"],
    [1849, "hpùng", "f×xU Ìjw\\w„"],
    [1850, "bùng", "ex´ e´w„"],
    [1851, "mùng", "Ìbm, ´wRø„"],
    [1852, "yùng", "g"],
    [1853, "rùng", "AwbwlZ, Kwjøwêlt„"],
    [1854, "lùng", "DVw„"],
    [1855, "wùng", "gpl K´w„"],
    [1856, "sùng", "b’„"],
    [1857, "hùng", "xgLøwZ„"],
    [1858, "", "È´ gYê(D)lMZ gø™d gYê(Z)Ë´ Aìæ Ìpw\\w m²„"],
    [1859, "ùt", "xMxl ÌeËlw\\w„"],
    [1860, "kùt", "g"],
    [1861, "hkùt", "Ìcw\\w, xoR„"],
    [1862, "gùt", "ey ÌLw\\w„"],
    [1863, "ngùt", "ew´w, oqi Ìpw\\w„"],
    [1864, "chyùt", "ÌewxZ xbtw„"],
    [1865, "tsùt", "ÌiwPw„"],
    [1866, "jùt", "e´w„"],
    [1867, "ñùt", "g"],
    [1868, "tùt", "Ìjw´w xbtw„"],
    [1869, "htùt", "g"],
    [1870, "nùt", "dÄ Kx´ ÌeËlw\\w„"],
    [1871, "pùt", "UÖi„"],
    [1872, "hpùt", "Mwx´ xbtw„"],
    [1873, "bùt", "g"],
    [1874, "mùt", "eL´w„"],
    [1875, "yùt", "g"],
    [1876, "rùt", "g"],
    [1877, "lùt", "ÌowiwB e´w„"],
    [1878, "wùt", "RÖB f×Kw, CUw„"],
    [1879, "sùt", "oóex£, AwVÖ\\w„"],
    [1880, "shùt", "hÔl K´w, Ìbwnw„"],
    [1881, "", "È´ gYê(D)lMZ gø™d gYê(d)Ë´ Aìæ Ìpw\\w m²„"],
    [1882, "ùn", "Ì¢ßwc K´w„"],
    [1883, "kùn", "p’t gw„"],
    [1884, "hkùn", "xgm 20„"],
    [1885, "gùn", "Ñl f×´w„"],
    [1886, "ngùn", "K"],
    [1887, "chyùn", "ex´Ëmwc K´w„"],
    [1888, "tsùn", "ÌKw\\w„"],
    [1889, "jùn", "ÌewZw, iÖK¥êiw bwxLl K´w„"],
    [1890, "ñùn", "K"],
    [1891, "tùn", "xgRw„"],
    [1892, "htùn", "PÖxU Ñp Ìjw\\w„"],
    [1893, "dùn", "Udw„"],
    [1894, "pùn", "INwxl ÌeËlw\\w„"],
    [1895, "h", "MQ, xe¬w„"],
    [1896, "b", "xo^Pw„"],
    [1897, "m", "Ìdwi„"],
    [1898, "y", "xPvËf# ex´twl´ AÄi Kdøw„"],
    [1899, "r", "LÖxl xbtw gw Ìixl xbtw„"],
    [1900, "l", "Ìcw^\\w D´Ø\\w„"],
    [1901, "w", "K"],
    [1902, "s", "Gwx´, gwxMPw„"],
    [1903, "shùn", "K^ew„"],
    [1904, "", "È´ gYê(D)lMZ gø™d gYê(e)Ë´ Aìæ Ìpw\\w m²„"],
    [1905, "ùp", "mwod K´w„"],
    [1906, "kùp", "K"],
    [1907, "hkùp", "ÌK^pw„"],
    [1908, "gùp", "xe¬w UÖxe BZøwxb„"],
    [1909, "ngùp", "Zl iÔ´Kx´ e´w„"],
    [1910, "chyùp", "K"],
    [1911, "tsùp", "K"],
    [1912, "jùp", "ÌMwU LÖ\\w, Riw Ìpw\\w„"],
    [1913, "tùp", "K"],
    [1914, "htùp", "iÖVw„"],
    [1915, "nùp", "K"],
    [1916, "pùp", "K"],
    [1917, "hpùp", "K"],
    [1918, "bùp", "iÔLê, AK´w„"],
    [1919, "mùp", "U×K×´w U×K×´w KUw„"],
    [1920, "yùp", "Â\\w„"],
    [1921, "rùp", "bxlI\\w„"],
    [1922, "lùp", "Ix´mwly, ÌewZw„"],
    [1923, "wùp", "K"],
    [1924, "sùp", "Xlw„"],
    [1925, "shùp", "gwcw K´w„"],
    [1926, "hùp", "iÖV, GËKlËM„"],
    [1927, "", "È´ gYê(D)lMZ gø™d gYê(i)Ë´ Aìæ Ìpw\\w m²„"],
    [1928, "ùm", "iÖLþÿ Ìpw\\w„"],
    [1929, "kùm", "Ìg´ xbtw„"],
    [1930, "hkùm", "Mw´ØZ Â\\w, m´y´„"],
    [1931, "gùm", "pwDlw„"],
    [1932, "ngùm", "f×Pf×Pw„"],
    [1933, "chyùm", "Aaê, gÖ´™y„"],
    [1934, "tsùm", "K"],
    [1935, "jùm", "xdiL„"],
    [1936, "ñùm", "K"],
    [1937, "tùm", "†xU, gyR„"],
    [1938, "h", "Aìæ Ìpw\\w, Ìmn Ìpw\\w„"],
    [1939, "dùm", "gËRw\\w„"],
    [1940, "nùm", "þèy, ixplw, eZíy„"],
    [1941, "pùm", "Riw, ARoÞ„"],
    [1942, "hpùm", "Iixd Ìlw\\w,owgxZ c´w„"],
    [1943, "bùm", "egµêZ, ewpw´„"],
    [1944, "mùm", "K"],
    [1945, "yùm", "Zl iÔ´ K´w„"],
    [1946, "rùm", "e´w, eZd Ìpw\\w„"],
    [1947, "lùm", "iÖLZ h´wB Ìlw\\w„"],
    [1948, "wùm", "K"],
    [1949, "sùm", "dÖKPwd Ìpw\\w, UxO N´„"],
    [1950, "shùm", "K"],
    [1951, "", "È´ gYê(G)lMZovËjwMy Ñp MVY Ìpw\\w m²„"],
    [1952, "kè", "xWxOZ ÌPxe c´w„"],
    [1953, "hkè", "Gx´ Ìjw\\w gw G´wB ÌeËlw\\w„"],
    [1954, "gè", "e"],
    [1955, "ngè", "e"],
    [1956, "chyè", "flw, LÖZw„"],
    [1957, "tsè", "e"],
    [1958, "jè", "e"],
    [1959, "ñè", "e"],
    [1960, "tè", "e"],
    [1961, "htè", "lMZ, Xwlw„"],
    [1962, "dè", "Ñl„"],
    [1963, "pè", "Xwlw„"],
    [1964, "hpè", "e"],
    [1965, "byè", "MPKw„"],
    [1966, "mè", "Ìp´wB Ìjw\\w„"],
    [1967, "yè", "e"],
    [1968, "rè", "Kwxs Ìlw\\w„"],
    [1969, "lè", "Awxghêw\\ Ìpw\\w, IlwB Apw gw Ìjw\\w„"],
    [1970, "wè", "ÌhwUw„"],
    [1971, "sè", "e"],
    [1972, "shè", "e"],
    [1973, "hè", "e"],
    [1974, "", "È´ gYê(G)lMZ gø™d gYê(O)Ë´ Aìæ Ìpw\\w m²„"],
    [1975, "kèng", "K"],
    [1976, "hkèng", "K"],
    [1977, "gèng", "K"],
    [1978, "ngèng", "KwxRtw K´w„"],
    [1979, "chyèng", "xPxZKw„"],
    [1980, "tsèng", "K"],
    [1981, "jèng", "oÖþÿ„"],
    [1982, "ñèng", "bwxs„"],
    [1983, "tèng", "xUKw lËMw\\w, Kwr iw´w„"],
    [1984, "htèng", "RÖB RËlw\\w, PÖ\\w„"],
    [1985, "dèng", "lq K´w, iwBl, ÌoB oitZ„"],
    [1986, "nèng", "ÂgÐl gwM´w„"],
    [1987, "pèng", "Awšw xbtw, LËUw\\w„"],
    [1988, "hpèng", "K"],
    [1989, "bèng", "K"],
    [1990, "myèng", "K"],
    [1991, "yèng", "K"],
    [1992, "rèng", "K"],
    [1993, "lèng", "K"],
    [1994, "wèng", "K"],
    [1995, "sèng", "K"],
    [1996, "shèng", "K"],
    [1997, "hèng", "K"],
    [1998, "", "È´ gYê(I)lMZ gø™d gYê(O)Ë´ Aìæ Ìpw\\w m²„"],
    [1999, "kòng", "gpl K´w„"],
    [2000, "hkòng", "Ìgtw ÌMw¬„"],
    [2001, "gòng", "K"],
    [2002, "ngòng", "xplw„"],
    [2003, "chyòng", "ixëb´, xgpw´„"],
    [2004, "tsòng", "K"],
    [2005, "jòng", "ht lMw„"],
    [2006, "ñòng", "K"],
    [2007, "tòng", "ÌRw´w„"],
    [2008, "htòng", "pwËZË´ PÖ\\w, ÌXwl„"],
    [2009, "dòng", "bÙmøit„"],
    [2010, "nòng", "Xgl, xb xbtw„"],
    [2011, "pòng", "K"],
    [2012, "hpòng", "g¬ Ìpw\\w„"],
    [2013, "bòng", "hwM Kx´ Ìlw\\w„"],
    [2014, "mòng", "K"],
    [2015, "yòng", "oiMÞ, oiþæ„"],
    [2016, "ròng", "AìæxdêxpZ Ìpw\\w„"],
    [2017, "lòng", "eÞxZËjwxMZw K´w„"],
    [2018, "wòng", "gpl„"],
    [2019, "sòng", "†´ØZòeÔYê„"],
    [2020, "shòng", "AwM´, AwMZ„"],
    [2021, "hòng", "px´Yw´ xPT´„"],
    [2022, "", "È´ gYê (AwB) lMZ MVd Ìpw\\w m²„"],
    [2023, "a", "GK, hwl, “Ìpw\\w” x¢ßtw eb´ gZêiwd Kwl„"],
    [2024, "kài", "xe¬w (KwYf×xl), xPvËf# ex´twl´ ezéi Kdøw„"],
    [2025, "h", "IliwB ´Lw, ´Ø\\w„"],
    [2026, "g", "gÉZ„"],
    [2027, "n", "iB„"],
    [2028, "c", "ÌLlw, ¢ßyWw K´w„"],
    [2029, "t", "Pwfw Ìpw\\w gw K´w„"],
    [2030, "j", "gø\\pw´ K´w„"],
    [2031, "t", "D£´ xbtw, Ìpw\\w„"],
    [2032, "h", "dwOl, pwl Ìgw\\w„"],
    [2033, "d", "ÌPwKw, ÌoB„"],
    [2034, "n", "AwlÖ, KPÖ, eËKw\\w„"],
    [2035, "p", "gw^I„"],
    [2036, "m", "hwl Ìew\\w, hwl„"],
    [2037, "y", "LÖxl Ìjw\\w„"],
    [2038, "r", "p’t, gt gþç„"],
    [2039, "lai", "xeQ Ìelw, dyxZ xdti,AwP´Y, Ahøwo„"],
    [2040, "w", "gw glw„"],
    [2041, "h", "g´ ÌPwKw„"],
    [2042, "", "È´ gYê (DB) lMZ MVd Ìpw\\w m²„"],
    [2043, "k", "K"],
    [2044, "h", "xPKw´ K´w„"],
    [2045, "g", "K×K×´„"],
    [2046, "n", "lwËpÐK, ow\\cwËd„"],
    [2047, "c", "xPlwB K´w„"],
    [2048, "t", "K"],
    [2049, "t", "eKw, (LÉ BZøwxb)„"],
    [2050, "h", "NÖPw iw´w„"],
    [2051, "d", "xiVw„"],
    [2052, "n", "K"],
    [2053, "p", "oËewdZ ht ÌLw\\w„"],
    [2054, "h", "gZwp gxl Ìjw\\w„"],
    [2055, "b", "K"],
    [2056, "m", "†xs Ìpw\\w, pRi Ìpw\\w„"],
    [2057, "y", "K"],
    [2058, "r", "K"],
    [2059, "w", "elwB e¢v xbtw„"],
    [2060, "s", "K"],
    [2061, "s", "K"],
    [2062, "h", "K"],
    [2063, "", "È´ gYê (J) lMZ MVd Ìpw\\w m²„"],
    [2064, "k", "ÌelwB xbtw, ZøwM K´w„"],
    [2065, "hkau", "Ìo\\d K´w,LÖlwly gw ÌRËV´y„"],
    [2066, "h", "DVw„"],
    [2067, "g", "PËlw\\w, ÌLbw„"],
    [2068, "n", "g"],
    [2069, "c", "g"],
    [2070, "t", "g"],
    [2071, "j", "DVw, xhq×„"],
    [2072, "ñ", "ÌiK×´y´ xPT´„"],
    [2073, "tau", "MÞpY K´w, Awb´Yy RËd\\w, xgmòwo K´w„"],
    [2074, "h", "bwË´ KUw„"],
    [2075, "d", "fxP Ìjw\\w,lwxM c´w„"],
    [2076, "n", "ÌgxQ„"],
    [2077, "p", "MMYw„"],
    [2078, "h", "g"],
    [2079, "b", "g´Zwl„"],
    [2080, "m", "AwPx´Z Ìpw\\w„"],
    [2081, "y", "g"],
    [2082, "r", "AwRx´ Ìew\\w, GËK lËM„"],
    [2083, "l", "IlUwB xbtw„"],
    [2084, "w", "hÖKw„"],
    [2085, "s", "ÌZl, Pxgê, iwLd„"],
    [2086, "s", "g"],
    [2087, "h", "g"],
    [2088, "", "È´ gYê (H) lMZ MVd Ìpw\\w m²„"],
    [2089, "k", "AwZx´ aKw gw Ìjw\\w„"],
    [2090, "h", "cw´Z Ìlw\\w gw xbtw„"],
    [2091, "g", "‘Z’, WwK xbtw„"],
    [2092, "n", "gRw gw m² K´w„"],
    [2093, "c", "exg¢, Rdw„"],
    [2094, "t", "g"],
    [2095, "j", "Ìo´„"],
    [2096, "ñ", "g"],
    [2097, "t", "g"],
    [2098, "h", "Ìewp´„"],
    [2099, "d", "lwLÖxU c´w„"],
    [2100, "n", "Iliw, fl lMw„"],
    [2101, "p", "Duo\\, Ìilw, gZwpZ Dx´ Ìjw\\w„"],
    [2102, "h", "MyZË´ eÞmvow K´w„"],
    [2103, "n", "g"],
    [2104, "m", "AwMZ, AZyZ KwlZ„"],
    [2105, "y", "g"],
    [2106, "r", "KÄ xbtw„"],
    [2107, "l", "p’g ew´w„"],
    [2108, "w", "g"],
    [2109, "s", "g"],
    [2110, "s", "g"],
    [2111, "h", "g"],
    [2112, "Jinghpò", "xPvËf#owdxipxlm²„"],
    [2113, "A", "gK gK K´w„"],
    [2114, "Ahkó ahkáng", "døwxtK hwËg AdÖixZ Ìew\\w„"],
    [2115, "Akyú kusô n galô ai", "bwd bxqYw BZøwxb ÌKxZtwI dK´w„"],
    [2116, "Akyú", "lq xgpyd iwdÖp„"],
    [2117, "Akyú", "AaêeÔYê, fleÞb„"],
    [2118, "Akyú", "Aaê xgpyd„"],
    [2119, "Akyú", "eÔYø MÞpY K´w„"],
    [2120, "Akyú", "Awxmgµêwb xbtw„"],
    [2121, "Akyáng gajâ ai.", "Px´¢gwd„"],
    [2122, "Akyáng  n gajâ ai.", "Px´¢pyd„"],
    [2123, "Aky", "oit A-oit dRdw„"],
    [2124, "Agajòng shá dáp prû ai.", "fUKÐK IlwB Apw„"],
    [2125, "Atsám ròng ai.", "mx£ßiwd„"],
    [2126, "Atsin sim ré ngá ai", "iwZ diZwÐK aKw„"],
    [2127, "Anà anà ngâ ai.", "AdÖejÖ£ß Kaw ÌKw\\w„"],
    [2128, "Anâ kàp ai.", "Ì´wM lMw„"],
    [2129, "Anâ htá ai.", "Ì´wM IKw„"],
    [2130, "Anî ahkrî shagâ ai.", "gÉZ xiVw xiVwiwZ iwZw„"],
    [2131, "Akring akrâng ré ai.", "ÌbxLgÐl A-Â\\dy„"],
    [2132, "Akroi anoi ré ai.", "ÌlËZ´w-ÌfËZ´w„"],
    [2133, "Ahkrit ayà ré ai.", "htwdK„"],
    [2134, "Ahkrit sòn ai.", "ht lMw„"],
    [2135, "Kàp anâ.", "xgtew Ì´wM„"],
    [2136, "Kám gatâ machyang.", "hwMøpyd eÖ´Øn„"],
    [2137, "K", "hwMø gw Kewl hwl„"],
    [2138, "Kám n gajâ ai.", "hwMø gw Kewl Ìgtw„"],
    [2139, "Kám òng ai.", "hwMø f×xUl„"],
    [2140, "Kám n òng ai.", "Kewl dÖf×xUËl„"],
    [2141, "Kumla madun ai.", "BxŠZ K´w„"],
    [2142, "Kohpâ pong.", "†icwd´___?"],
    [2143, "Komì pà.", "K×^xptw´´ ÌL´„"],
    [2144, "Komì rin jàk.", "K×^xptw´ Ìe´w jìè„"],
    [2145, "Koi gam ai.", "AwZx´ Ìjw\\„"],
    [2146, "Koi kau ai", "AwZ´w p’l, Gx´ xbtw p’l„"],
    [2147, "Kriket ginsup poi.", "x¢ßËKUz ÌLl„"],
    [2148, "Hkà hkyét ai.", "ewdy ÂKwB Ìjw\\w„"],
    [2149, "Hkà jà ai.", "ewdy ÌZwlw„"],
    [2150, "Hkà tung ai.", "Ñd ewdy gw´w„"],
    [2151, "Hkà htung.", "eÖûK´Yy, eÖLÖ´y„"],
    [2152, "Hkà bong", "eÖLÖ´y„"],
    [2153, "Hkà lim sanghpó.", "PwgzËix´d, ewdWÖgy RwpwR„"],
    [2154, "Hkà lung gá.", "gwxl Pwex´„"],
    [2155, "Hkà lui hkrat ai", "ewdygw dbyÐg aKw„"],
    [2156, "Hkà yông ai", "ewdy gw dby Ñg aKw„"],
    [2157, "Hkà shin ai.", "Mw Ìcw\\w„"],
    [2158, "Hkàp tau lá ai", "Awb´Yy RËdw\\w„"],
    [2159, "Hkàm shá ai.", "bÖL gw KÄ ÌhwMw„"],
    [2160, "Hk", "opø Kx´g ew´w„"],
    [2161, "Hk", "Aopø„"],
    [2162, "Hkoi lâ ai.", "cw´Z Ìlw\\w„"],
    [2163, "Hkoi lang ai.", "cw´ Ñl gø\\pw´ K´w„"],
    [2164, "Hkoi", "cw´Z xbtw„"],
    [2165, "Hkum chyúp ai.", "oóeÔYê„"],
    [2166, "Hkung ran ai.", "xgtw eZw„"],
    [2167, "Hkung ran poi.", "xggwp iŠlø Duo\\„"],
    [2168, "Hkung ran chyalu num.", "xggwxpZw ixplw„"],
    [2169, "Hkung ran chyalu lâ.", "xggwxpZ eÖ´Øn„"],
    [2170, "Hkum n manû ai.", "Mhê\\Zy A\\þÿw„"],
    [2171, "Hkritung hpai ai.", "Mhê\\Zy Ìpw\\w„"],
    [2172, "Gahkyin gumdin ngá ai.", "xixl RÖxl aKw„"],
    [2173, "Gachying galang shá ai.", "ÌKPw ÌiPwËK ÌLw\\w„"],
    [2174, "Gajam galam", "Aohø AwP´Y„PUzfUw„"],
    [2175, "Gajòng gapòng prû sâ ai", "AKPiwu IlwB e´w„"],
    [2176, "Gabû lóm sai!", "AoËìæwn eÞKwm Kx´ËQw!"],
    [2177, "Gahtam galà yû ai.", "KwxU KÖxU ÌPw\\w„ AËþ¢wePw´„"],
    [2178, "Garì gawà ngâ ai.", "idPél Ìpw\\w„"],
    [2179, "Gamung gamân shangôn ai.", "Awlwe AwËlwPdw K´w„"],
    [2180, "Gayâ gayoi ngâ ai", "LËRw\\w„ LRxZ DVw„"],
    [2181, "Gayà jahpà", "lwR gyR Ìpw\\w„"],
    [2182, "Gayà gatâ.", "xdlwR„"],
    [2183, "Gasàt hkàt ai.", "jÖ¦ K´w„"],
    [2184, "Gasàt gàn ai.", "KwxRtw K´w„"],
    [2185, "Gamù hkàt ai.", "iÁ jÖ¦ K´w„"],
    [2186, "Gamù gàn ai.", "§ëb jÖ¦ K´w„"],
    # [2186, "Gamù gàn ai.", "§ë b jÖ¦ K´w„"],
    [2187, "Gàm garan ai.", "xgh£ß K´w„"],
    [2188, "Gàm shá ai.", "lËM hwËM ÌLw\\w„"],
    [2189, "Gá n mû shagâ ai.", "Aohø Kaw ÌKw\\w„"],
    [2190, "Gá ginhtim", "odôZ Ìpw\\w„"],
    [2191, "Gá jahtá chyai ai.", "Mez Pez iw´w„"],
    [2192, "Gá jahkrup ai", "A\\Ëmn xdYêt Ìlw\\w„"],
    [2193, "Gáp shingjòng ai.", "†xltw †xlK´w„"],
    [2194, "Ginrót ginrang.", "BfwËl xofwËl Ñl f×´w„"],
    [2195, "Gumròng gu", "iwd oiôwd d´LwÐK Kaw ÌKw\\w„"],
    [2196, "Gông gùm ai.", "gÙ¦ Ìpw\\w„"],
    [2197, "Grup win.", "ex´o´, ex´Ëgm„"],
    [2198, "Ngà hkui ai.", "iwQ c´w„"],
    [2199, "Ngá shá ginra.", "gwoþÿwd„"],
    [2200, "Chye hkrum ai.", "gÉ Rdw Âdw„"],
    [2201, "Chye chyeng ai.", "gÉmÞßZ, šwdy„"],
    [2202, "Chye náng ai.", "AgMZ Ìpw\\w, šwZ Ìpw\\w„"],
    [2203, "Chye madát ai.", "gÖxR Ìlw\\w, AdÖh\\ Ìpw\\w„"],
    [2204, "Chyejú gabá sai.", "AwËewdwÐl cdøgwb awxKl„"],
    [2205, "Chyejú dùm dàt ai.", "AwËewdwK KÚZšZw šwed Kx´ËQw„"],
    [2206, "Tsùn dàn ai.", "eÞKwm K´w„"],
    [2207, "Tsùn shanáng ai", "Rwdxd xbtw„"],
    [2208, "Tsùn shaprò ai.", "iìægø AwMgËsw\\w„"],
    [2209, "Tàng madun ai", ".ÌNwnYw K´w„"],
    [2210, "Tàm dagrang ai.", "xgQwx´ f×´w„"],
    [2211, "Tâm jò ai.", "bëb xbtw„"],
    [2212, "Tám htám ai.", "bëb ÌhwMw„"],
    [2213, "Htim gasàt ai.", "Aw¢ßiY K´w„"],
    [2214, "Htum wá ai/ Htum mát ai.", "Aìæ ex´l„"],
    [2215, "Htòng shang ai.", "ÌRlZ Ìowiw„"],
    [2216, "Htòng dá ai.", "xeQ ÌeËlw\\w, AwMgwxs Ìjw\\w„"],
    [2217, "Htò wá ai.", "xoPx´ Ìjw\\w„"],
    [2218, "Htòt kau ai.", "gblwB xbtw„"],
    [2219, "Dabung dùm ai.", "iÙZK´ gwËg gwbø jìè gËRw\\w„"],
    [2220, "Dip shaprò ai.", "ovÆ´Y K´w„"],
    [2221, "Dù bòng ai.", "xWxO f×lw Ìgiw´ Ìew\\w„"],
    [2222, "Dù manat kau ai.", "xWxO ÌPew xb gc K´w„"],
    [2223, "Dôm kau ai.", "þÿxMZK´w„"],
    [2224, "N sen rim ai.", "Awd´ Lg´ Âdw„"],
    [2225, "Nsen rim jàk.", "x´xPhw´„"],
    [2226, "N sen shapoi ai.", "eÞPw´ K´w„"],
    [2227, "N sen shapoi jàk", "Ì´xWA eÞPw´ K´w jìè„"],
    [2228, "N sen shalun jàk.", "lwDWz þeyKw´„"],
    [2229, "Nàt kàp ai.", "hÔZ lMw„"],
    [2230, "Nàt jò ai.", "gxl xbtw„"],
    [2231, "Nan galô ai.", "eÖd´wB K´w„"],
    [2232, "Nahpang nadû.", "Klw Aw´Ø Ìgwgw„"],
    [2233, "Nàm dùm.", "ewBLwdw„"],
    [2234, "Nàm sâ ai.", "il ZøwM Kx´g Ìjw\\w„"],
    [2235, "Namsi namsó.", "fliÔl„"],
    [2236, "Nò kù chyòng.", "MyRêw N´„"],
    [2237, "Páng tòn ai.", "Ìjw´w xbtw„"],
    [2238, "Páng dàt ai.", "AwiìèY K´w„"],
    [2239, "Pàt shingdang ai.", "gwcw xbtw„"],
    [2240, "Pát/prát ting", "AwRy\\d Kwl„"],
    [2241, "Poi tung.", "Ìilw´ PxlZ A\\þÿw„"],
    [2242, "Poi bò.", "Ìilw´ Aw´º xbd„"],
    [2243, "Poi woi.", "Ìilw´ Aìæ xbd„"],
    [2244, "Prát htum ai.", "AìæKwl Apw, iÙZÖø g´Y K´w„"],
    [2245, "Pyôlung pyôlang.", "gwË´ ´pdytw„"],
    [2246, "Pyô dik ai.", "xgËdwbeÔYê„"],
    [2247, "Pyô shá ai.", "f×xZê K´w„"],
    [2248, "Hpàng jahtum.", "A\\ËmnZ„"],
    [2249, "Hpò tsùn ai.", "gYêdw K´w, LÖxl ÌKw\\w„"],
    [2250, "Hpòt nì.", "Apw Kwxl„"],
    [2251, "Hpòt yà.", "hx\\nøu„"],
    [2252, "Jinghpò shatâ ni.", "xPvËf# iwp„"],
    [2253, "Râ tâ", "gpwM„"],
    [2254, "Wut tâ", "ÌRV„"],
    [2255, "Shala", "Awnw´"],
    [2256, "Jahtum tâ", "mwId„"],
    [2257, "Shangan tâ", "hwb„"],
    [2258, "Simri tâ", "Awxpd„"],
    [2259, "Gupsi tâ", "KwxZ„"],
    [2260, "Guptung tâ", "AwËNwd„"],
    [2261, "Kala tâ/Ladi tâ", "Ìewp„"],
    [2262, "Maji tâ", "iwN„"],
    [2263, "Magá tâ", "fw†d„"],
    [2264, "Hkú tâ", "P’Z„"],
    [2265, "Jinghpò Ahkyng Masa.", "xPvËf# FÙZÖ„"],
    [2266, "Ninglum tâ", "m´u Kwl„"],
    [2267, "Ningshung tâ", "myZ Kwl„"],
    [2268, "Mangai tâ", "goìæ„"],
    [2269, "Yinam tâ", "gnêw Kwl„"],
    [2270, "Jinghpò n htoi ni.", "xPvËf# gw´„"],
    [2271, "Laban", "ÌbD/´xg gw´„"],
    [2272, "Laban", "Ìowi gw´„"],
    [2273, "Laban", "iŠl gw´„"],
    [2274, "Laban", "gÖc gw´„"],
    [2275, "Laban", "gÙpþexZ gw´„"],
    [2276, "Laban", "Â¢ß gw´„"],
    [2277, "Laban", "mxd gw´„"],
    [2278, "Bàt", "o®wp„"],
    [2279, "Jinghpò sòn htí ai làm.", "xPvËf# MYdw„"],
    [2280, "Namsi namsó, hpunsi wahkyí", "fliÖl„"],
    [2281, "Ó", "i"],
    [2282, "Hkainu si.", "Wwxli„"],
    [2283, "Hkyé magó si.", "i"],
    [2284, "Gala ginsap si", "i"],
    [2285, "Ganje si.", "ZwËiwl„"],
    [2286, "Ginshau si.", "xP´wl„"],
    [2287, "Ginhkyan si.", "xZÉ„"],
    [2288, "Ginsau si", "Z´iÖR„"],
    [2289, "Gumchyai shalui.", "Kilw„"],
    [2290, "Chahkya si.", "Awilqy„"],
    [2291, "Tsan lun si.", "i"],
    [2292, "Tsamin si.", "ÌLRÖ´„"],
    [2293, "Chyaga si", "i"],
    [2294, "Jangwom si.", "Awdw´o„"],
    [2295, "Já magó si.", "AwËel„"],
    [2296, "Nâ manai si.", "i"],
    [2297, "N gâ malang si.", "iwxUKVwl„"],
    [2298, "Nò hkun si.", "Pydw gwbwi„"],
    [2299, "Namsi tum.", "gwbwi„"],
    [2300, "Pongmuk si.", "i"],
    [2301, "Batan si.", "i"],
    [2302, "Ma un si.", "dwx´Kl„"],
    [2303, "Makòk si.", "Ai´w„"],
    [2304, "Mahkó si.", "gM´y„"],
    [2305, "Magyeng si.", "i"],
    [2306, "Magó si.", "dwPexZ„"],
    [2307, "M", "KVwl„"],
    [2308, "Malaga si.", "icÖx´ Awi„"],
    [2309, "Langû si.", "Kl„"],
    [2310, "Luidui si.", "´gwg ÌUOw„"],
    [2311, "Luipi si.", "ÌdiÖ„"],
    [2312, "Luihpom si.", "i"],
    [2313, "Labri si.", "i"],
    [2314, "Luiba si.", "g´ ÌUOw„"],
    [2315, "Wamyi si.", "i"],
    [2316, "Sahká si", "i"],
    [2317, "Sabyi si.", "AwOÖ´„"],
    [2318, "Sabyin si.", "i"],
    [2319, "Shalui si.", "ÌUOw„"],
    [2320, "Si mai si mó, si n mì.", "mwK ewPxl„lwI„†icwd„Ry´w„ÌXKytw„xZt^p„f×l Kxg„xmilÖ AwlÖ„KRlKytw„†l ix´P„MwR´„g¬wKxg„cxdtw„Wwl ÌPxd„ÌZR ewZ„ZÖlmy iPlw„gw´ly„MwR´„ÌKË´lw„ÌgËOdw„LÖU×´w mwK„ZÖlmy iPlw„KI´py„"],
]
